
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BOMItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BOMItem
 * 
 */
export type BOMItemModel = runtime.Types.Result.DefaultSelection<Prisma.$BOMItemPayload>

export type AggregateBOMItem = {
  _count: BOMItemCountAggregateOutputType | null
  _avg: BOMItemAvgAggregateOutputType | null
  _sum: BOMItemSumAggregateOutputType | null
  _min: BOMItemMinAggregateOutputType | null
  _max: BOMItemMaxAggregateOutputType | null
}

export type BOMItemAvgAggregateOutputType = {
  id: number | null
  quantity: runtime.Decimal | null
  unitCost: runtime.Decimal | null
  productId: number | null
  componentId: number | null
}

export type BOMItemSumAggregateOutputType = {
  id: number | null
  quantity: runtime.Decimal | null
  unitCost: runtime.Decimal | null
  productId: number | null
  componentId: number | null
}

export type BOMItemMinAggregateOutputType = {
  id: number | null
  quantity: runtime.Decimal | null
  unitCost: runtime.Decimal | null
  notes: string | null
  productId: number | null
  componentId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BOMItemMaxAggregateOutputType = {
  id: number | null
  quantity: runtime.Decimal | null
  unitCost: runtime.Decimal | null
  notes: string | null
  productId: number | null
  componentId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BOMItemCountAggregateOutputType = {
  id: number
  quantity: number
  unitCost: number
  notes: number
  productId: number
  componentId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BOMItemAvgAggregateInputType = {
  id?: true
  quantity?: true
  unitCost?: true
  productId?: true
  componentId?: true
}

export type BOMItemSumAggregateInputType = {
  id?: true
  quantity?: true
  unitCost?: true
  productId?: true
  componentId?: true
}

export type BOMItemMinAggregateInputType = {
  id?: true
  quantity?: true
  unitCost?: true
  notes?: true
  productId?: true
  componentId?: true
  createdAt?: true
  updatedAt?: true
}

export type BOMItemMaxAggregateInputType = {
  id?: true
  quantity?: true
  unitCost?: true
  notes?: true
  productId?: true
  componentId?: true
  createdAt?: true
  updatedAt?: true
}

export type BOMItemCountAggregateInputType = {
  id?: true
  quantity?: true
  unitCost?: true
  notes?: true
  productId?: true
  componentId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BOMItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BOMItem to aggregate.
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BOMItems to fetch.
   */
  orderBy?: Prisma.BOMItemOrderByWithRelationInput | Prisma.BOMItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BOMItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BOMItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BOMItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BOMItems
  **/
  _count?: true | BOMItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BOMItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BOMItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BOMItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BOMItemMaxAggregateInputType
}

export type GetBOMItemAggregateType<T extends BOMItemAggregateArgs> = {
      [P in keyof T & keyof AggregateBOMItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBOMItem[P]>
    : Prisma.GetScalarType<T[P], AggregateBOMItem[P]>
}




export type BOMItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BOMItemWhereInput
  orderBy?: Prisma.BOMItemOrderByWithAggregationInput | Prisma.BOMItemOrderByWithAggregationInput[]
  by: Prisma.BOMItemScalarFieldEnum[] | Prisma.BOMItemScalarFieldEnum
  having?: Prisma.BOMItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BOMItemCountAggregateInputType | true
  _avg?: BOMItemAvgAggregateInputType
  _sum?: BOMItemSumAggregateInputType
  _min?: BOMItemMinAggregateInputType
  _max?: BOMItemMaxAggregateInputType
}

export type BOMItemGroupByOutputType = {
  id: number
  quantity: runtime.Decimal
  unitCost: runtime.Decimal | null
  notes: string | null
  productId: number
  componentId: number
  createdAt: Date
  updatedAt: Date
  _count: BOMItemCountAggregateOutputType | null
  _avg: BOMItemAvgAggregateOutputType | null
  _sum: BOMItemSumAggregateOutputType | null
  _min: BOMItemMinAggregateOutputType | null
  _max: BOMItemMaxAggregateOutputType | null
}

type GetBOMItemGroupByPayload<T extends BOMItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BOMItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BOMItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BOMItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BOMItemGroupByOutputType[P]>
      }
    >
  >



export type BOMItemWhereInput = {
  AND?: Prisma.BOMItemWhereInput | Prisma.BOMItemWhereInput[]
  OR?: Prisma.BOMItemWhereInput[]
  NOT?: Prisma.BOMItemWhereInput | Prisma.BOMItemWhereInput[]
  id?: Prisma.IntFilter<"BOMItem"> | number
  quantity?: Prisma.DecimalFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.DecimalNullableFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"BOMItem"> | string | null
  productId?: Prisma.IntFilter<"BOMItem"> | number
  componentId?: Prisma.IntFilter<"BOMItem"> | number
  createdAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  component?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type BOMItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  component?: Prisma.ProductOrderByWithRelationInput
}

export type BOMItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  productId_componentId?: Prisma.BOMItemProductIdComponentIdCompoundUniqueInput
  AND?: Prisma.BOMItemWhereInput | Prisma.BOMItemWhereInput[]
  OR?: Prisma.BOMItemWhereInput[]
  NOT?: Prisma.BOMItemWhereInput | Prisma.BOMItemWhereInput[]
  quantity?: Prisma.DecimalFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.DecimalNullableFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"BOMItem"> | string | null
  productId?: Prisma.IntFilter<"BOMItem"> | number
  componentId?: Prisma.IntFilter<"BOMItem"> | number
  createdAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  component?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id" | "productId_componentId">

export type BOMItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BOMItemCountOrderByAggregateInput
  _avg?: Prisma.BOMItemAvgOrderByAggregateInput
  _max?: Prisma.BOMItemMaxOrderByAggregateInput
  _min?: Prisma.BOMItemMinOrderByAggregateInput
  _sum?: Prisma.BOMItemSumOrderByAggregateInput
}

export type BOMItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.BOMItemScalarWhereWithAggregatesInput | Prisma.BOMItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.BOMItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BOMItemScalarWhereWithAggregatesInput | Prisma.BOMItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BOMItem"> | number
  quantity?: Prisma.DecimalWithAggregatesFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.DecimalNullableWithAggregatesFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"BOMItem"> | string | null
  productId?: Prisma.IntWithAggregatesFilter<"BOMItem"> | number
  componentId?: Prisma.IntWithAggregatesFilter<"BOMItem"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BOMItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BOMItem"> | Date | string
}

export type BOMItemCreateInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutBomItemsInput
  component: Prisma.ProductCreateNestedOneWithoutBomComponentsInput
}

export type BOMItemUncheckedCreateInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  productId: number
  componentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemUpdateInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutBomItemsNestedInput
  component?: Prisma.ProductUpdateOneRequiredWithoutBomComponentsNestedInput
}

export type BOMItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemCreateManyInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  productId: number
  componentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemUpdateManyMutationInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemListRelationFilter = {
  every?: Prisma.BOMItemWhereInput
  some?: Prisma.BOMItemWhereInput
  none?: Prisma.BOMItemWhereInput
}

export type BOMItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BOMItemProductIdComponentIdCompoundUniqueInput = {
  productId: number
  componentId: number
}

export type BOMItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BOMItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
}

export type BOMItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BOMItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BOMItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
}

export type BOMItemCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput> | Prisma.BOMItemCreateWithoutProductInput[] | Prisma.BOMItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutProductInput | Prisma.BOMItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.BOMItemCreateManyProductInputEnvelope
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
}

export type BOMItemCreateNestedManyWithoutComponentInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput> | Prisma.BOMItemCreateWithoutComponentInput[] | Prisma.BOMItemUncheckedCreateWithoutComponentInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutComponentInput | Prisma.BOMItemCreateOrConnectWithoutComponentInput[]
  createMany?: Prisma.BOMItemCreateManyComponentInputEnvelope
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
}

export type BOMItemUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput> | Prisma.BOMItemCreateWithoutProductInput[] | Prisma.BOMItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutProductInput | Prisma.BOMItemCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.BOMItemCreateManyProductInputEnvelope
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
}

export type BOMItemUncheckedCreateNestedManyWithoutComponentInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput> | Prisma.BOMItemCreateWithoutComponentInput[] | Prisma.BOMItemUncheckedCreateWithoutComponentInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutComponentInput | Prisma.BOMItemCreateOrConnectWithoutComponentInput[]
  createMany?: Prisma.BOMItemCreateManyComponentInputEnvelope
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
}

export type BOMItemUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput> | Prisma.BOMItemCreateWithoutProductInput[] | Prisma.BOMItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutProductInput | Prisma.BOMItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.BOMItemUpsertWithWhereUniqueWithoutProductInput | Prisma.BOMItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.BOMItemCreateManyProductInputEnvelope
  set?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  disconnect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  delete?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  update?: Prisma.BOMItemUpdateWithWhereUniqueWithoutProductInput | Prisma.BOMItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.BOMItemUpdateManyWithWhereWithoutProductInput | Prisma.BOMItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
}

export type BOMItemUpdateManyWithoutComponentNestedInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput> | Prisma.BOMItemCreateWithoutComponentInput[] | Prisma.BOMItemUncheckedCreateWithoutComponentInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutComponentInput | Prisma.BOMItemCreateOrConnectWithoutComponentInput[]
  upsert?: Prisma.BOMItemUpsertWithWhereUniqueWithoutComponentInput | Prisma.BOMItemUpsertWithWhereUniqueWithoutComponentInput[]
  createMany?: Prisma.BOMItemCreateManyComponentInputEnvelope
  set?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  disconnect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  delete?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  update?: Prisma.BOMItemUpdateWithWhereUniqueWithoutComponentInput | Prisma.BOMItemUpdateWithWhereUniqueWithoutComponentInput[]
  updateMany?: Prisma.BOMItemUpdateManyWithWhereWithoutComponentInput | Prisma.BOMItemUpdateManyWithWhereWithoutComponentInput[]
  deleteMany?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
}

export type BOMItemUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput> | Prisma.BOMItemCreateWithoutProductInput[] | Prisma.BOMItemUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutProductInput | Prisma.BOMItemCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.BOMItemUpsertWithWhereUniqueWithoutProductInput | Prisma.BOMItemUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.BOMItemCreateManyProductInputEnvelope
  set?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  disconnect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  delete?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  update?: Prisma.BOMItemUpdateWithWhereUniqueWithoutProductInput | Prisma.BOMItemUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.BOMItemUpdateManyWithWhereWithoutProductInput | Prisma.BOMItemUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
}

export type BOMItemUncheckedUpdateManyWithoutComponentNestedInput = {
  create?: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput> | Prisma.BOMItemCreateWithoutComponentInput[] | Prisma.BOMItemUncheckedCreateWithoutComponentInput[]
  connectOrCreate?: Prisma.BOMItemCreateOrConnectWithoutComponentInput | Prisma.BOMItemCreateOrConnectWithoutComponentInput[]
  upsert?: Prisma.BOMItemUpsertWithWhereUniqueWithoutComponentInput | Prisma.BOMItemUpsertWithWhereUniqueWithoutComponentInput[]
  createMany?: Prisma.BOMItemCreateManyComponentInputEnvelope
  set?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  disconnect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  delete?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  connect?: Prisma.BOMItemWhereUniqueInput | Prisma.BOMItemWhereUniqueInput[]
  update?: Prisma.BOMItemUpdateWithWhereUniqueWithoutComponentInput | Prisma.BOMItemUpdateWithWhereUniqueWithoutComponentInput[]
  updateMany?: Prisma.BOMItemUpdateManyWithWhereWithoutComponentInput | Prisma.BOMItemUpdateManyWithWhereWithoutComponentInput[]
  deleteMany?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
}

export type BOMItemCreateWithoutProductInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  component: Prisma.ProductCreateNestedOneWithoutBomComponentsInput
}

export type BOMItemUncheckedCreateWithoutProductInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  componentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemCreateOrConnectWithoutProductInput = {
  where: Prisma.BOMItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput>
}

export type BOMItemCreateManyProductInputEnvelope = {
  data: Prisma.BOMItemCreateManyProductInput | Prisma.BOMItemCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type BOMItemCreateWithoutComponentInput = {
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutBomItemsInput
}

export type BOMItemUncheckedCreateWithoutComponentInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  productId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemCreateOrConnectWithoutComponentInput = {
  where: Prisma.BOMItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput>
}

export type BOMItemCreateManyComponentInputEnvelope = {
  data: Prisma.BOMItemCreateManyComponentInput | Prisma.BOMItemCreateManyComponentInput[]
  skipDuplicates?: boolean
}

export type BOMItemUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.BOMItemWhereUniqueInput
  update: Prisma.XOR<Prisma.BOMItemUpdateWithoutProductInput, Prisma.BOMItemUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.BOMItemCreateWithoutProductInput, Prisma.BOMItemUncheckedCreateWithoutProductInput>
}

export type BOMItemUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.BOMItemWhereUniqueInput
  data: Prisma.XOR<Prisma.BOMItemUpdateWithoutProductInput, Prisma.BOMItemUncheckedUpdateWithoutProductInput>
}

export type BOMItemUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.BOMItemScalarWhereInput
  data: Prisma.XOR<Prisma.BOMItemUpdateManyMutationInput, Prisma.BOMItemUncheckedUpdateManyWithoutProductInput>
}

export type BOMItemScalarWhereInput = {
  AND?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
  OR?: Prisma.BOMItemScalarWhereInput[]
  NOT?: Prisma.BOMItemScalarWhereInput | Prisma.BOMItemScalarWhereInput[]
  id?: Prisma.IntFilter<"BOMItem"> | number
  quantity?: Prisma.DecimalFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.DecimalNullableFilter<"BOMItem"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.StringNullableFilter<"BOMItem"> | string | null
  productId?: Prisma.IntFilter<"BOMItem"> | number
  componentId?: Prisma.IntFilter<"BOMItem"> | number
  createdAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BOMItem"> | Date | string
}

export type BOMItemUpsertWithWhereUniqueWithoutComponentInput = {
  where: Prisma.BOMItemWhereUniqueInput
  update: Prisma.XOR<Prisma.BOMItemUpdateWithoutComponentInput, Prisma.BOMItemUncheckedUpdateWithoutComponentInput>
  create: Prisma.XOR<Prisma.BOMItemCreateWithoutComponentInput, Prisma.BOMItemUncheckedCreateWithoutComponentInput>
}

export type BOMItemUpdateWithWhereUniqueWithoutComponentInput = {
  where: Prisma.BOMItemWhereUniqueInput
  data: Prisma.XOR<Prisma.BOMItemUpdateWithoutComponentInput, Prisma.BOMItemUncheckedUpdateWithoutComponentInput>
}

export type BOMItemUpdateManyWithWhereWithoutComponentInput = {
  where: Prisma.BOMItemScalarWhereInput
  data: Prisma.XOR<Prisma.BOMItemUpdateManyMutationInput, Prisma.BOMItemUncheckedUpdateManyWithoutComponentInput>
}

export type BOMItemCreateManyProductInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  componentId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemCreateManyComponentInput = {
  id?: number
  quantity: runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: string | null
  productId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BOMItemUpdateWithoutProductInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  component?: Prisma.ProductUpdateOneRequiredWithoutBomComponentsNestedInput
}

export type BOMItemUncheckedUpdateWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemUpdateWithoutComponentInput = {
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutBomItemsNestedInput
}

export type BOMItemUncheckedUpdateWithoutComponentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BOMItemUncheckedUpdateManyWithoutComponentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BOMItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quantity?: boolean
  unitCost?: boolean
  notes?: boolean
  productId?: boolean
  componentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bOMItem"]>

export type BOMItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quantity?: boolean
  unitCost?: boolean
  notes?: boolean
  productId?: boolean
  componentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bOMItem"]>

export type BOMItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quantity?: boolean
  unitCost?: boolean
  notes?: boolean
  productId?: boolean
  componentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bOMItem"]>

export type BOMItemSelectScalar = {
  id?: boolean
  quantity?: boolean
  unitCost?: boolean
  notes?: boolean
  productId?: boolean
  componentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BOMItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "quantity" | "unitCost" | "notes" | "productId" | "componentId" | "createdAt" | "updatedAt", ExtArgs["result"]["bOMItem"]>
export type BOMItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type BOMItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type BOMItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  component?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $BOMItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BOMItem"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    component: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    quantity: runtime.Decimal
    unitCost: runtime.Decimal | null
    notes: string | null
    productId: number
    componentId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["bOMItem"]>
  composites: {}
}

export type BOMItemGetPayload<S extends boolean | null | undefined | BOMItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BOMItemPayload, S>

export type BOMItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BOMItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BOMItemCountAggregateInputType | true
  }

export interface BOMItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BOMItem'], meta: { name: 'BOMItem' } }
  /**
   * Find zero or one BOMItem that matches the filter.
   * @param {BOMItemFindUniqueArgs} args - Arguments to find a BOMItem
   * @example
   * // Get one BOMItem
   * const bOMItem = await prisma.bOMItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BOMItemFindUniqueArgs>(args: Prisma.SelectSubset<T, BOMItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BOMItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BOMItemFindUniqueOrThrowArgs} args - Arguments to find a BOMItem
   * @example
   * // Get one BOMItem
   * const bOMItem = await prisma.bOMItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BOMItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BOMItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BOMItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemFindFirstArgs} args - Arguments to find a BOMItem
   * @example
   * // Get one BOMItem
   * const bOMItem = await prisma.bOMItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BOMItemFindFirstArgs>(args?: Prisma.SelectSubset<T, BOMItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BOMItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemFindFirstOrThrowArgs} args - Arguments to find a BOMItem
   * @example
   * // Get one BOMItem
   * const bOMItem = await prisma.bOMItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BOMItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BOMItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BOMItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BOMItems
   * const bOMItems = await prisma.bOMItem.findMany()
   * 
   * // Get first 10 BOMItems
   * const bOMItems = await prisma.bOMItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bOMItemWithIdOnly = await prisma.bOMItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BOMItemFindManyArgs>(args?: Prisma.SelectSubset<T, BOMItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BOMItem.
   * @param {BOMItemCreateArgs} args - Arguments to create a BOMItem.
   * @example
   * // Create one BOMItem
   * const BOMItem = await prisma.bOMItem.create({
   *   data: {
   *     // ... data to create a BOMItem
   *   }
   * })
   * 
   */
  create<T extends BOMItemCreateArgs>(args: Prisma.SelectSubset<T, BOMItemCreateArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BOMItems.
   * @param {BOMItemCreateManyArgs} args - Arguments to create many BOMItems.
   * @example
   * // Create many BOMItems
   * const bOMItem = await prisma.bOMItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BOMItemCreateManyArgs>(args?: Prisma.SelectSubset<T, BOMItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BOMItems and returns the data saved in the database.
   * @param {BOMItemCreateManyAndReturnArgs} args - Arguments to create many BOMItems.
   * @example
   * // Create many BOMItems
   * const bOMItem = await prisma.bOMItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BOMItems and only return the `id`
   * const bOMItemWithIdOnly = await prisma.bOMItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BOMItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BOMItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BOMItem.
   * @param {BOMItemDeleteArgs} args - Arguments to delete one BOMItem.
   * @example
   * // Delete one BOMItem
   * const BOMItem = await prisma.bOMItem.delete({
   *   where: {
   *     // ... filter to delete one BOMItem
   *   }
   * })
   * 
   */
  delete<T extends BOMItemDeleteArgs>(args: Prisma.SelectSubset<T, BOMItemDeleteArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BOMItem.
   * @param {BOMItemUpdateArgs} args - Arguments to update one BOMItem.
   * @example
   * // Update one BOMItem
   * const bOMItem = await prisma.bOMItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BOMItemUpdateArgs>(args: Prisma.SelectSubset<T, BOMItemUpdateArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BOMItems.
   * @param {BOMItemDeleteManyArgs} args - Arguments to filter BOMItems to delete.
   * @example
   * // Delete a few BOMItems
   * const { count } = await prisma.bOMItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BOMItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, BOMItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BOMItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BOMItems
   * const bOMItem = await prisma.bOMItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BOMItemUpdateManyArgs>(args: Prisma.SelectSubset<T, BOMItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BOMItems and returns the data updated in the database.
   * @param {BOMItemUpdateManyAndReturnArgs} args - Arguments to update many BOMItems.
   * @example
   * // Update many BOMItems
   * const bOMItem = await prisma.bOMItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BOMItems and only return the `id`
   * const bOMItemWithIdOnly = await prisma.bOMItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BOMItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BOMItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BOMItem.
   * @param {BOMItemUpsertArgs} args - Arguments to update or create a BOMItem.
   * @example
   * // Update or create a BOMItem
   * const bOMItem = await prisma.bOMItem.upsert({
   *   create: {
   *     // ... data to create a BOMItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BOMItem we want to update
   *   }
   * })
   */
  upsert<T extends BOMItemUpsertArgs>(args: Prisma.SelectSubset<T, BOMItemUpsertArgs<ExtArgs>>): Prisma.Prisma__BOMItemClient<runtime.Types.Result.GetResult<Prisma.$BOMItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BOMItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemCountArgs} args - Arguments to filter BOMItems to count.
   * @example
   * // Count the number of BOMItems
   * const count = await prisma.bOMItem.count({
   *   where: {
   *     // ... the filter for the BOMItems we want to count
   *   }
   * })
  **/
  count<T extends BOMItemCountArgs>(
    args?: Prisma.Subset<T, BOMItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BOMItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BOMItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BOMItemAggregateArgs>(args: Prisma.Subset<T, BOMItemAggregateArgs>): Prisma.PrismaPromise<GetBOMItemAggregateType<T>>

  /**
   * Group by BOMItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BOMItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BOMItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BOMItemGroupByArgs['orderBy'] }
      : { orderBy?: BOMItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BOMItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBOMItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BOMItem model
 */
readonly fields: BOMItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BOMItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BOMItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  component<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BOMItem model
 */
export interface BOMItemFieldRefs {
  readonly id: Prisma.FieldRef<"BOMItem", 'Int'>
  readonly quantity: Prisma.FieldRef<"BOMItem", 'Decimal'>
  readonly unitCost: Prisma.FieldRef<"BOMItem", 'Decimal'>
  readonly notes: Prisma.FieldRef<"BOMItem", 'String'>
  readonly productId: Prisma.FieldRef<"BOMItem", 'Int'>
  readonly componentId: Prisma.FieldRef<"BOMItem", 'Int'>
  readonly createdAt: Prisma.FieldRef<"BOMItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BOMItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BOMItem findUnique
 */
export type BOMItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter, which BOMItem to fetch.
   */
  where: Prisma.BOMItemWhereUniqueInput
}

/**
 * BOMItem findUniqueOrThrow
 */
export type BOMItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter, which BOMItem to fetch.
   */
  where: Prisma.BOMItemWhereUniqueInput
}

/**
 * BOMItem findFirst
 */
export type BOMItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter, which BOMItem to fetch.
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BOMItems to fetch.
   */
  orderBy?: Prisma.BOMItemOrderByWithRelationInput | Prisma.BOMItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BOMItems.
   */
  cursor?: Prisma.BOMItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BOMItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BOMItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BOMItems.
   */
  distinct?: Prisma.BOMItemScalarFieldEnum | Prisma.BOMItemScalarFieldEnum[]
}

/**
 * BOMItem findFirstOrThrow
 */
export type BOMItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter, which BOMItem to fetch.
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BOMItems to fetch.
   */
  orderBy?: Prisma.BOMItemOrderByWithRelationInput | Prisma.BOMItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BOMItems.
   */
  cursor?: Prisma.BOMItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BOMItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BOMItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BOMItems.
   */
  distinct?: Prisma.BOMItemScalarFieldEnum | Prisma.BOMItemScalarFieldEnum[]
}

/**
 * BOMItem findMany
 */
export type BOMItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter, which BOMItems to fetch.
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BOMItems to fetch.
   */
  orderBy?: Prisma.BOMItemOrderByWithRelationInput | Prisma.BOMItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BOMItems.
   */
  cursor?: Prisma.BOMItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BOMItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BOMItems.
   */
  skip?: number
  distinct?: Prisma.BOMItemScalarFieldEnum | Prisma.BOMItemScalarFieldEnum[]
}

/**
 * BOMItem create
 */
export type BOMItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * The data needed to create a BOMItem.
   */
  data: Prisma.XOR<Prisma.BOMItemCreateInput, Prisma.BOMItemUncheckedCreateInput>
}

/**
 * BOMItem createMany
 */
export type BOMItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BOMItems.
   */
  data: Prisma.BOMItemCreateManyInput | Prisma.BOMItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BOMItem createManyAndReturn
 */
export type BOMItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * The data used to create many BOMItems.
   */
  data: Prisma.BOMItemCreateManyInput | Prisma.BOMItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BOMItem update
 */
export type BOMItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * The data needed to update a BOMItem.
   */
  data: Prisma.XOR<Prisma.BOMItemUpdateInput, Prisma.BOMItemUncheckedUpdateInput>
  /**
   * Choose, which BOMItem to update.
   */
  where: Prisma.BOMItemWhereUniqueInput
}

/**
 * BOMItem updateMany
 */
export type BOMItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BOMItems.
   */
  data: Prisma.XOR<Prisma.BOMItemUpdateManyMutationInput, Prisma.BOMItemUncheckedUpdateManyInput>
  /**
   * Filter which BOMItems to update
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * Limit how many BOMItems to update.
   */
  limit?: number
}

/**
 * BOMItem updateManyAndReturn
 */
export type BOMItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * The data used to update BOMItems.
   */
  data: Prisma.XOR<Prisma.BOMItemUpdateManyMutationInput, Prisma.BOMItemUncheckedUpdateManyInput>
  /**
   * Filter which BOMItems to update
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * Limit how many BOMItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BOMItem upsert
 */
export type BOMItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * The filter to search for the BOMItem to update in case it exists.
   */
  where: Prisma.BOMItemWhereUniqueInput
  /**
   * In case the BOMItem found by the `where` argument doesn't exist, create a new BOMItem with this data.
   */
  create: Prisma.XOR<Prisma.BOMItemCreateInput, Prisma.BOMItemUncheckedCreateInput>
  /**
   * In case the BOMItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BOMItemUpdateInput, Prisma.BOMItemUncheckedUpdateInput>
}

/**
 * BOMItem delete
 */
export type BOMItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
  /**
   * Filter which BOMItem to delete.
   */
  where: Prisma.BOMItemWhereUniqueInput
}

/**
 * BOMItem deleteMany
 */
export type BOMItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BOMItems to delete
   */
  where?: Prisma.BOMItemWhereInput
  /**
   * Limit how many BOMItems to delete.
   */
  limit?: number
}

/**
 * BOMItem without action
 */
export type BOMItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BOMItem
   */
  select?: Prisma.BOMItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BOMItem
   */
  omit?: Prisma.BOMItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BOMItemInclude<ExtArgs> | null
}
