
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Customers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Customers
 * 
 */
export type CustomersModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomersPayload>

export type AggregateCustomers = {
  _count: CustomersCountAggregateOutputType | null
  _avg: CustomersAvgAggregateOutputType | null
  _sum: CustomersSumAggregateOutputType | null
  _min: CustomersMinAggregateOutputType | null
  _max: CustomersMaxAggregateOutputType | null
}

export type CustomersAvgAggregateOutputType = {
  id: number | null
}

export type CustomersSumAggregateOutputType = {
  id: number | null
}

export type CustomersMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  code: string | null
  image: string | null
  status: string | null
  phone: string | null
  address: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomersMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  code: string | null
  image: string | null
  status: string | null
  phone: string | null
  address: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomersCountAggregateOutputType = {
  id: number
  name: number
  email: number
  code: number
  image: number
  status: number
  phone: number
  address: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CustomersAvgAggregateInputType = {
  id?: true
}

export type CustomersSumAggregateInputType = {
  id?: true
}

export type CustomersMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  code?: true
  image?: true
  status?: true
  phone?: true
  address?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomersMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  code?: true
  image?: true
  status?: true
  phone?: true
  address?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomersCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  code?: true
  image?: true
  status?: true
  phone?: true
  address?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CustomersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customers to aggregate.
   */
  where?: Prisma.CustomersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomersOrderByWithRelationInput | Prisma.CustomersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Customers
  **/
  _count?: true | CustomersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomersMaxAggregateInputType
}

export type GetCustomersAggregateType<T extends CustomersAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomers[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomers[P]>
}




export type CustomersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomersWhereInput
  orderBy?: Prisma.CustomersOrderByWithAggregationInput | Prisma.CustomersOrderByWithAggregationInput[]
  by: Prisma.CustomersScalarFieldEnum[] | Prisma.CustomersScalarFieldEnum
  having?: Prisma.CustomersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomersCountAggregateInputType | true
  _avg?: CustomersAvgAggregateInputType
  _sum?: CustomersSumAggregateInputType
  _min?: CustomersMinAggregateInputType
  _max?: CustomersMaxAggregateInputType
}

export type CustomersGroupByOutputType = {
  id: number
  name: string | null
  email: string | null
  code: string | null
  image: string | null
  status: string
  phone: string | null
  address: string | null
  createdAt: Date
  updatedAt: Date | null
  _count: CustomersCountAggregateOutputType | null
  _avg: CustomersAvgAggregateOutputType | null
  _sum: CustomersSumAggregateOutputType | null
  _min: CustomersMinAggregateOutputType | null
  _max: CustomersMaxAggregateOutputType | null
}

type GetCustomersGroupByPayload<T extends CustomersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomersGroupByOutputType[P]>
      }
    >
  >



export type CustomersWhereInput = {
  AND?: Prisma.CustomersWhereInput | Prisma.CustomersWhereInput[]
  OR?: Prisma.CustomersWhereInput[]
  NOT?: Prisma.CustomersWhereInput | Prisma.CustomersWhereInput[]
  id?: Prisma.IntFilter<"Customers"> | number
  name?: Prisma.StringNullableFilter<"Customers"> | string | null
  email?: Prisma.StringNullableFilter<"Customers"> | string | null
  code?: Prisma.StringNullableFilter<"Customers"> | string | null
  image?: Prisma.StringNullableFilter<"Customers"> | string | null
  status?: Prisma.StringFilter<"Customers"> | string
  phone?: Prisma.StringNullableFilter<"Customers"> | string | null
  address?: Prisma.StringNullableFilter<"Customers"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customers"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Customers"> | Date | string | null
}

export type CustomersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type CustomersWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CustomersWhereInput | Prisma.CustomersWhereInput[]
  OR?: Prisma.CustomersWhereInput[]
  NOT?: Prisma.CustomersWhereInput | Prisma.CustomersWhereInput[]
  name?: Prisma.StringNullableFilter<"Customers"> | string | null
  email?: Prisma.StringNullableFilter<"Customers"> | string | null
  code?: Prisma.StringNullableFilter<"Customers"> | string | null
  image?: Prisma.StringNullableFilter<"Customers"> | string | null
  status?: Prisma.StringFilter<"Customers"> | string
  phone?: Prisma.StringNullableFilter<"Customers"> | string | null
  address?: Prisma.StringNullableFilter<"Customers"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customers"> | Date | string
  updatedAt?: Prisma.DateTimeNullableFilter<"Customers"> | Date | string | null
}, "id">

export type CustomersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CustomersCountOrderByAggregateInput
  _avg?: Prisma.CustomersAvgOrderByAggregateInput
  _max?: Prisma.CustomersMaxOrderByAggregateInput
  _min?: Prisma.CustomersMinOrderByAggregateInput
  _sum?: Prisma.CustomersSumOrderByAggregateInput
}

export type CustomersScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomersScalarWhereWithAggregatesInput | Prisma.CustomersScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomersScalarWhereWithAggregatesInput | Prisma.CustomersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Customers"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  code?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  image?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"Customers"> | string
  phone?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Customers"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Customers"> | Date | string
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Customers"> | Date | string | null
}

export type CustomersCreateInput = {
  name?: string | null
  email?: string | null
  code?: string | null
  image?: string | null
  status?: string
  phone?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type CustomersUncheckedCreateInput = {
  id?: number
  name?: string | null
  email?: string | null
  code?: string | null
  image?: string | null
  status?: string
  phone?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type CustomersUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CustomersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CustomersCreateManyInput = {
  id?: number
  name?: string | null
  email?: string | null
  code?: string | null
  image?: string | null
  status?: string
  phone?: string | null
  address?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string | null
}

export type CustomersUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CustomersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type CustomersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CustomersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  code?: Prisma.SortOrder
  image?: Prisma.SortOrder
  status?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type CustomersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  phone?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["customers"]>

export type CustomersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  phone?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["customers"]>

export type CustomersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  phone?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["customers"]>

export type CustomersSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  code?: boolean
  image?: boolean
  status?: boolean
  phone?: boolean
  address?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CustomersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "code" | "image" | "status" | "phone" | "address" | "createdAt" | "updatedAt", ExtArgs["result"]["customers"]>

export type $CustomersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Customers"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    email: string | null
    code: string | null
    image: string | null
    status: string
    phone: string | null
    address: string | null
    createdAt: Date
    updatedAt: Date | null
  }, ExtArgs["result"]["customers"]>
  composites: {}
}

export type CustomersGetPayload<S extends boolean | null | undefined | CustomersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomersPayload, S>

export type CustomersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomersCountAggregateInputType | true
  }

export interface CustomersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Customers'], meta: { name: 'Customers' } }
  /**
   * Find zero or one Customers that matches the filter.
   * @param {CustomersFindUniqueArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomersFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Customers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomersFindUniqueOrThrowArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersFindFirstArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomersFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomersFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersFindFirstOrThrowArgs} args - Arguments to find a Customers
   * @example
   * // Get one Customers
   * const customers = await prisma.customers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Customers
   * const customers = await prisma.customers.findMany()
   * 
   * // Get first 10 Customers
   * const customers = await prisma.customers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customersWithIdOnly = await prisma.customers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomersFindManyArgs>(args?: Prisma.SelectSubset<T, CustomersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Customers.
   * @param {CustomersCreateArgs} args - Arguments to create a Customers.
   * @example
   * // Create one Customers
   * const Customers = await prisma.customers.create({
   *   data: {
   *     // ... data to create a Customers
   *   }
   * })
   * 
   */
  create<T extends CustomersCreateArgs>(args: Prisma.SelectSubset<T, CustomersCreateArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Customers.
   * @param {CustomersCreateManyArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customers = await prisma.customers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomersCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Customers and returns the data saved in the database.
   * @param {CustomersCreateManyAndReturnArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customers = await prisma.customers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Customers and only return the `id`
   * const customersWithIdOnly = await prisma.customers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Customers.
   * @param {CustomersDeleteArgs} args - Arguments to delete one Customers.
   * @example
   * // Delete one Customers
   * const Customers = await prisma.customers.delete({
   *   where: {
   *     // ... filter to delete one Customers
   *   }
   * })
   * 
   */
  delete<T extends CustomersDeleteArgs>(args: Prisma.SelectSubset<T, CustomersDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Customers.
   * @param {CustomersUpdateArgs} args - Arguments to update one Customers.
   * @example
   * // Update one Customers
   * const customers = await prisma.customers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomersUpdateArgs>(args: Prisma.SelectSubset<T, CustomersUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Customers.
   * @param {CustomersDeleteManyArgs} args - Arguments to filter Customers to delete.
   * @example
   * // Delete a few Customers
   * const { count } = await prisma.customers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomersDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Customers
   * const customers = await prisma.customers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomersUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers and returns the data updated in the database.
   * @param {CustomersUpdateManyAndReturnArgs} args - Arguments to update many Customers.
   * @example
   * // Update many Customers
   * const customers = await prisma.customers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Customers and only return the `id`
   * const customersWithIdOnly = await prisma.customers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Customers.
   * @param {CustomersUpsertArgs} args - Arguments to update or create a Customers.
   * @example
   * // Update or create a Customers
   * const customers = await prisma.customers.upsert({
   *   create: {
   *     // ... data to create a Customers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Customers we want to update
   *   }
   * })
   */
  upsert<T extends CustomersUpsertArgs>(args: Prisma.SelectSubset<T, CustomersUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomersClient<runtime.Types.Result.GetResult<Prisma.$CustomersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersCountArgs} args - Arguments to filter Customers to count.
   * @example
   * // Count the number of Customers
   * const count = await prisma.customers.count({
   *   where: {
   *     // ... the filter for the Customers we want to count
   *   }
   * })
  **/
  count<T extends CustomersCountArgs>(
    args?: Prisma.Subset<T, CustomersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomersAggregateArgs>(args: Prisma.Subset<T, CustomersAggregateArgs>): Prisma.PrismaPromise<GetCustomersAggregateType<T>>

  /**
   * Group by Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomersGroupByArgs['orderBy'] }
      : { orderBy?: CustomersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Customers model
 */
readonly fields: CustomersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Customers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Customers model
 */
export interface CustomersFieldRefs {
  readonly id: Prisma.FieldRef<"Customers", 'Int'>
  readonly name: Prisma.FieldRef<"Customers", 'String'>
  readonly email: Prisma.FieldRef<"Customers", 'String'>
  readonly code: Prisma.FieldRef<"Customers", 'String'>
  readonly image: Prisma.FieldRef<"Customers", 'String'>
  readonly status: Prisma.FieldRef<"Customers", 'String'>
  readonly phone: Prisma.FieldRef<"Customers", 'String'>
  readonly address: Prisma.FieldRef<"Customers", 'String'>
  readonly createdAt: Prisma.FieldRef<"Customers", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Customers", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Customers findUnique
 */
export type CustomersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where: Prisma.CustomersWhereUniqueInput
}

/**
 * Customers findUniqueOrThrow
 */
export type CustomersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where: Prisma.CustomersWhereUniqueInput
}

/**
 * Customers findFirst
 */
export type CustomersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where?: Prisma.CustomersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomersOrderByWithRelationInput | Prisma.CustomersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * Customers findFirstOrThrow
 */
export type CustomersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where?: Prisma.CustomersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomersOrderByWithRelationInput | Prisma.CustomersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * Customers findMany
 */
export type CustomersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where?: Prisma.CustomersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomersOrderByWithRelationInput | Prisma.CustomersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Customers.
   */
  cursor?: Prisma.CustomersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  distinct?: Prisma.CustomersScalarFieldEnum | Prisma.CustomersScalarFieldEnum[]
}

/**
 * Customers create
 */
export type CustomersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * The data needed to create a Customers.
   */
  data?: Prisma.XOR<Prisma.CustomersCreateInput, Prisma.CustomersUncheckedCreateInput>
}

/**
 * Customers createMany
 */
export type CustomersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Customers.
   */
  data: Prisma.CustomersCreateManyInput | Prisma.CustomersCreateManyInput[]
}

/**
 * Customers createManyAndReturn
 */
export type CustomersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * The data used to create many Customers.
   */
  data: Prisma.CustomersCreateManyInput | Prisma.CustomersCreateManyInput[]
}

/**
 * Customers update
 */
export type CustomersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * The data needed to update a Customers.
   */
  data: Prisma.XOR<Prisma.CustomersUpdateInput, Prisma.CustomersUncheckedUpdateInput>
  /**
   * Choose, which Customers to update.
   */
  where: Prisma.CustomersWhereUniqueInput
}

/**
 * Customers updateMany
 */
export type CustomersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Customers.
   */
  data: Prisma.XOR<Prisma.CustomersUpdateManyMutationInput, Prisma.CustomersUncheckedUpdateManyInput>
  /**
   * Filter which Customers to update
   */
  where?: Prisma.CustomersWhereInput
  /**
   * Limit how many Customers to update.
   */
  limit?: number
}

/**
 * Customers updateManyAndReturn
 */
export type CustomersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * The data used to update Customers.
   */
  data: Prisma.XOR<Prisma.CustomersUpdateManyMutationInput, Prisma.CustomersUncheckedUpdateManyInput>
  /**
   * Filter which Customers to update
   */
  where?: Prisma.CustomersWhereInput
  /**
   * Limit how many Customers to update.
   */
  limit?: number
}

/**
 * Customers upsert
 */
export type CustomersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * The filter to search for the Customers to update in case it exists.
   */
  where: Prisma.CustomersWhereUniqueInput
  /**
   * In case the Customers found by the `where` argument doesn't exist, create a new Customers with this data.
   */
  create: Prisma.XOR<Prisma.CustomersCreateInput, Prisma.CustomersUncheckedCreateInput>
  /**
   * In case the Customers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomersUpdateInput, Prisma.CustomersUncheckedUpdateInput>
}

/**
 * Customers delete
 */
export type CustomersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
  /**
   * Filter which Customers to delete.
   */
  where: Prisma.CustomersWhereUniqueInput
}

/**
 * Customers deleteMany
 */
export type CustomersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customers to delete
   */
  where?: Prisma.CustomersWhereInput
  /**
   * Limit how many Customers to delete.
   */
  limit?: number
}

/**
 * Customers without action
 */
export type CustomersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customers
   */
  select?: Prisma.CustomersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customers
   */
  omit?: Prisma.CustomersOmit<ExtArgs> | null
}
