
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Departments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Departments
 * 
 */
export type DepartmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$DepartmentsPayload>

export type AggregateDepartments = {
  _count: DepartmentsCountAggregateOutputType | null
  _avg: DepartmentsAvgAggregateOutputType | null
  _sum: DepartmentsSumAggregateOutputType | null
  _min: DepartmentsMinAggregateOutputType | null
  _max: DepartmentsMaxAggregateOutputType | null
}

export type DepartmentsAvgAggregateOutputType = {
  id: number | null
}

export type DepartmentsSumAggregateOutputType = {
  id: number | null
}

export type DepartmentsMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type DepartmentsMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type DepartmentsCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type DepartmentsAvgAggregateInputType = {
  id?: true
}

export type DepartmentsSumAggregateInputType = {
  id?: true
}

export type DepartmentsMinAggregateInputType = {
  id?: true
  name?: true
}

export type DepartmentsMaxAggregateInputType = {
  id?: true
  name?: true
}

export type DepartmentsCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type DepartmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Departments to aggregate.
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Departments to fetch.
   */
  orderBy?: Prisma.DepartmentsOrderByWithRelationInput | Prisma.DepartmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DepartmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Departments
  **/
  _count?: true | DepartmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DepartmentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DepartmentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DepartmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DepartmentsMaxAggregateInputType
}

export type GetDepartmentsAggregateType<T extends DepartmentsAggregateArgs> = {
      [P in keyof T & keyof AggregateDepartments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDepartments[P]>
    : Prisma.GetScalarType<T[P], AggregateDepartments[P]>
}




export type DepartmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DepartmentsWhereInput
  orderBy?: Prisma.DepartmentsOrderByWithAggregationInput | Prisma.DepartmentsOrderByWithAggregationInput[]
  by: Prisma.DepartmentsScalarFieldEnum[] | Prisma.DepartmentsScalarFieldEnum
  having?: Prisma.DepartmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DepartmentsCountAggregateInputType | true
  _avg?: DepartmentsAvgAggregateInputType
  _sum?: DepartmentsSumAggregateInputType
  _min?: DepartmentsMinAggregateInputType
  _max?: DepartmentsMaxAggregateInputType
}

export type DepartmentsGroupByOutputType = {
  id: number
  name: string
  _count: DepartmentsCountAggregateOutputType | null
  _avg: DepartmentsAvgAggregateOutputType | null
  _sum: DepartmentsSumAggregateOutputType | null
  _min: DepartmentsMinAggregateOutputType | null
  _max: DepartmentsMaxAggregateOutputType | null
}

type GetDepartmentsGroupByPayload<T extends DepartmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DepartmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DepartmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DepartmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DepartmentsGroupByOutputType[P]>
      }
    >
  >



export type DepartmentsWhereInput = {
  AND?: Prisma.DepartmentsWhereInput | Prisma.DepartmentsWhereInput[]
  OR?: Prisma.DepartmentsWhereInput[]
  NOT?: Prisma.DepartmentsWhereInput | Prisma.DepartmentsWhereInput[]
  id?: Prisma.IntFilter<"Departments"> | number
  name?: Prisma.StringFilter<"Departments"> | string
  employees?: Prisma.EmployeesListRelationFilter
}

export type DepartmentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  employees?: Prisma.EmployeesOrderByRelationAggregateInput
}

export type DepartmentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.DepartmentsWhereInput | Prisma.DepartmentsWhereInput[]
  OR?: Prisma.DepartmentsWhereInput[]
  NOT?: Prisma.DepartmentsWhereInput | Prisma.DepartmentsWhereInput[]
  name?: Prisma.StringFilter<"Departments"> | string
  employees?: Prisma.EmployeesListRelationFilter
}, "id">

export type DepartmentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.DepartmentsCountOrderByAggregateInput
  _avg?: Prisma.DepartmentsAvgOrderByAggregateInput
  _max?: Prisma.DepartmentsMaxOrderByAggregateInput
  _min?: Prisma.DepartmentsMinOrderByAggregateInput
  _sum?: Prisma.DepartmentsSumOrderByAggregateInput
}

export type DepartmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.DepartmentsScalarWhereWithAggregatesInput | Prisma.DepartmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.DepartmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DepartmentsScalarWhereWithAggregatesInput | Prisma.DepartmentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Departments"> | number
  name?: Prisma.StringWithAggregatesFilter<"Departments"> | string
}

export type DepartmentsCreateInput = {
  name: string
  employees?: Prisma.EmployeesCreateNestedManyWithoutDepartmentsInput
}

export type DepartmentsUncheckedCreateInput = {
  id?: number
  name: string
  employees?: Prisma.EmployeesUncheckedCreateNestedManyWithoutDepartmentsInput
}

export type DepartmentsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  employees?: Prisma.EmployeesUpdateManyWithoutDepartmentsNestedInput
}

export type DepartmentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  employees?: Prisma.EmployeesUncheckedUpdateManyWithoutDepartmentsNestedInput
}

export type DepartmentsCreateManyInput = {
  id?: number
  name: string
}

export type DepartmentsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DepartmentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DepartmentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type DepartmentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DepartmentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type DepartmentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type DepartmentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type DepartmentsNullableScalarRelationFilter = {
  is?: Prisma.DepartmentsWhereInput | null
  isNot?: Prisma.DepartmentsWhereInput | null
}

export type DepartmentsCreateNestedOneWithoutEmployeesInput = {
  create?: Prisma.XOR<Prisma.DepartmentsCreateWithoutEmployeesInput, Prisma.DepartmentsUncheckedCreateWithoutEmployeesInput>
  connectOrCreate?: Prisma.DepartmentsCreateOrConnectWithoutEmployeesInput
  connect?: Prisma.DepartmentsWhereUniqueInput
}

export type DepartmentsUpdateOneWithoutEmployeesNestedInput = {
  create?: Prisma.XOR<Prisma.DepartmentsCreateWithoutEmployeesInput, Prisma.DepartmentsUncheckedCreateWithoutEmployeesInput>
  connectOrCreate?: Prisma.DepartmentsCreateOrConnectWithoutEmployeesInput
  upsert?: Prisma.DepartmentsUpsertWithoutEmployeesInput
  disconnect?: Prisma.DepartmentsWhereInput | boolean
  delete?: Prisma.DepartmentsWhereInput | boolean
  connect?: Prisma.DepartmentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DepartmentsUpdateToOneWithWhereWithoutEmployeesInput, Prisma.DepartmentsUpdateWithoutEmployeesInput>, Prisma.DepartmentsUncheckedUpdateWithoutEmployeesInput>
}

export type DepartmentsCreateWithoutEmployeesInput = {
  name: string
}

export type DepartmentsUncheckedCreateWithoutEmployeesInput = {
  id?: number
  name: string
}

export type DepartmentsCreateOrConnectWithoutEmployeesInput = {
  where: Prisma.DepartmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.DepartmentsCreateWithoutEmployeesInput, Prisma.DepartmentsUncheckedCreateWithoutEmployeesInput>
}

export type DepartmentsUpsertWithoutEmployeesInput = {
  update: Prisma.XOR<Prisma.DepartmentsUpdateWithoutEmployeesInput, Prisma.DepartmentsUncheckedUpdateWithoutEmployeesInput>
  create: Prisma.XOR<Prisma.DepartmentsCreateWithoutEmployeesInput, Prisma.DepartmentsUncheckedCreateWithoutEmployeesInput>
  where?: Prisma.DepartmentsWhereInput
}

export type DepartmentsUpdateToOneWithWhereWithoutEmployeesInput = {
  where?: Prisma.DepartmentsWhereInput
  data: Prisma.XOR<Prisma.DepartmentsUpdateWithoutEmployeesInput, Prisma.DepartmentsUncheckedUpdateWithoutEmployeesInput>
}

export type DepartmentsUpdateWithoutEmployeesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DepartmentsUncheckedUpdateWithoutEmployeesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type DepartmentsCountOutputType
 */

export type DepartmentsCountOutputType = {
  employees: number
}

export type DepartmentsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employees?: boolean | DepartmentsCountOutputTypeCountEmployeesArgs
}

/**
 * DepartmentsCountOutputType without action
 */
export type DepartmentsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepartmentsCountOutputType
   */
  select?: Prisma.DepartmentsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DepartmentsCountOutputType without action
 */
export type DepartmentsCountOutputTypeCountEmployeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployeesWhereInput
}


export type DepartmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  employees?: boolean | Prisma.Departments$employeesArgs<ExtArgs>
  _count?: boolean | Prisma.DepartmentsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["departments"]>

export type DepartmentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["departments"]>

export type DepartmentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["departments"]>

export type DepartmentsSelectScalar = {
  id?: boolean
  name?: boolean
}

export type DepartmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["departments"]>
export type DepartmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employees?: boolean | Prisma.Departments$employeesArgs<ExtArgs>
  _count?: boolean | Prisma.DepartmentsCountOutputTypeDefaultArgs<ExtArgs>
}
export type DepartmentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type DepartmentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $DepartmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Departments"
  objects: {
    employees: Prisma.$EmployeesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["departments"]>
  composites: {}
}

export type DepartmentsGetPayload<S extends boolean | null | undefined | DepartmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload, S>

export type DepartmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DepartmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DepartmentsCountAggregateInputType | true
  }

export interface DepartmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Departments'], meta: { name: 'Departments' } }
  /**
   * Find zero or one Departments that matches the filter.
   * @param {DepartmentsFindUniqueArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DepartmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, DepartmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Departments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DepartmentsFindUniqueOrThrowArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DepartmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DepartmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Departments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsFindFirstArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DepartmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, DepartmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Departments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsFindFirstOrThrowArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DepartmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DepartmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Departments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Departments
   * const departments = await prisma.departments.findMany()
   * 
   * // Get first 10 Departments
   * const departments = await prisma.departments.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const departmentsWithIdOnly = await prisma.departments.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DepartmentsFindManyArgs>(args?: Prisma.SelectSubset<T, DepartmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Departments.
   * @param {DepartmentsCreateArgs} args - Arguments to create a Departments.
   * @example
   * // Create one Departments
   * const Departments = await prisma.departments.create({
   *   data: {
   *     // ... data to create a Departments
   *   }
   * })
   * 
   */
  create<T extends DepartmentsCreateArgs>(args: Prisma.SelectSubset<T, DepartmentsCreateArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Departments.
   * @param {DepartmentsCreateManyArgs} args - Arguments to create many Departments.
   * @example
   * // Create many Departments
   * const departments = await prisma.departments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DepartmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, DepartmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Departments and returns the data saved in the database.
   * @param {DepartmentsCreateManyAndReturnArgs} args - Arguments to create many Departments.
   * @example
   * // Create many Departments
   * const departments = await prisma.departments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Departments and only return the `id`
   * const departmentsWithIdOnly = await prisma.departments.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DepartmentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DepartmentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Departments.
   * @param {DepartmentsDeleteArgs} args - Arguments to delete one Departments.
   * @example
   * // Delete one Departments
   * const Departments = await prisma.departments.delete({
   *   where: {
   *     // ... filter to delete one Departments
   *   }
   * })
   * 
   */
  delete<T extends DepartmentsDeleteArgs>(args: Prisma.SelectSubset<T, DepartmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Departments.
   * @param {DepartmentsUpdateArgs} args - Arguments to update one Departments.
   * @example
   * // Update one Departments
   * const departments = await prisma.departments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DepartmentsUpdateArgs>(args: Prisma.SelectSubset<T, DepartmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Departments.
   * @param {DepartmentsDeleteManyArgs} args - Arguments to filter Departments to delete.
   * @example
   * // Delete a few Departments
   * const { count } = await prisma.departments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DepartmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, DepartmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Departments
   * const departments = await prisma.departments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DepartmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, DepartmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Departments and returns the data updated in the database.
   * @param {DepartmentsUpdateManyAndReturnArgs} args - Arguments to update many Departments.
   * @example
   * // Update many Departments
   * const departments = await prisma.departments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Departments and only return the `id`
   * const departmentsWithIdOnly = await prisma.departments.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DepartmentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DepartmentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Departments.
   * @param {DepartmentsUpsertArgs} args - Arguments to update or create a Departments.
   * @example
   * // Update or create a Departments
   * const departments = await prisma.departments.upsert({
   *   create: {
   *     // ... data to create a Departments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Departments we want to update
   *   }
   * })
   */
  upsert<T extends DepartmentsUpsertArgs>(args: Prisma.SelectSubset<T, DepartmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__DepartmentsClient<runtime.Types.Result.GetResult<Prisma.$DepartmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsCountArgs} args - Arguments to filter Departments to count.
   * @example
   * // Count the number of Departments
   * const count = await prisma.departments.count({
   *   where: {
   *     // ... the filter for the Departments we want to count
   *   }
   * })
  **/
  count<T extends DepartmentsCountArgs>(
    args?: Prisma.Subset<T, DepartmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DepartmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DepartmentsAggregateArgs>(args: Prisma.Subset<T, DepartmentsAggregateArgs>): Prisma.PrismaPromise<GetDepartmentsAggregateType<T>>

  /**
   * Group by Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DepartmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DepartmentsGroupByArgs['orderBy'] }
      : { orderBy?: DepartmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DepartmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDepartmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Departments model
 */
readonly fields: DepartmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Departments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DepartmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employees<T extends Prisma.Departments$employeesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Departments$employeesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Departments model
 */
export interface DepartmentsFieldRefs {
  readonly id: Prisma.FieldRef<"Departments", 'Int'>
  readonly name: Prisma.FieldRef<"Departments", 'String'>
}
    

// Custom InputTypes
/**
 * Departments findUnique
 */
export type DepartmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter, which Departments to fetch.
   */
  where: Prisma.DepartmentsWhereUniqueInput
}

/**
 * Departments findUniqueOrThrow
 */
export type DepartmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter, which Departments to fetch.
   */
  where: Prisma.DepartmentsWhereUniqueInput
}

/**
 * Departments findFirst
 */
export type DepartmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter, which Departments to fetch.
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Departments to fetch.
   */
  orderBy?: Prisma.DepartmentsOrderByWithRelationInput | Prisma.DepartmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Departments.
   */
  cursor?: Prisma.DepartmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Departments.
   */
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * Departments findFirstOrThrow
 */
export type DepartmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter, which Departments to fetch.
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Departments to fetch.
   */
  orderBy?: Prisma.DepartmentsOrderByWithRelationInput | Prisma.DepartmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Departments.
   */
  cursor?: Prisma.DepartmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Departments.
   */
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * Departments findMany
 */
export type DepartmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter, which Departments to fetch.
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Departments to fetch.
   */
  orderBy?: Prisma.DepartmentsOrderByWithRelationInput | Prisma.DepartmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Departments.
   */
  cursor?: Prisma.DepartmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Departments.
   */
  skip?: number
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * Departments create
 */
export type DepartmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a Departments.
   */
  data: Prisma.XOR<Prisma.DepartmentsCreateInput, Prisma.DepartmentsUncheckedCreateInput>
}

/**
 * Departments createMany
 */
export type DepartmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Departments.
   */
  data: Prisma.DepartmentsCreateManyInput | Prisma.DepartmentsCreateManyInput[]
}

/**
 * Departments createManyAndReturn
 */
export type DepartmentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * The data used to create many Departments.
   */
  data: Prisma.DepartmentsCreateManyInput | Prisma.DepartmentsCreateManyInput[]
}

/**
 * Departments update
 */
export type DepartmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a Departments.
   */
  data: Prisma.XOR<Prisma.DepartmentsUpdateInput, Prisma.DepartmentsUncheckedUpdateInput>
  /**
   * Choose, which Departments to update.
   */
  where: Prisma.DepartmentsWhereUniqueInput
}

/**
 * Departments updateMany
 */
export type DepartmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Departments.
   */
  data: Prisma.XOR<Prisma.DepartmentsUpdateManyMutationInput, Prisma.DepartmentsUncheckedUpdateManyInput>
  /**
   * Filter which Departments to update
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * Limit how many Departments to update.
   */
  limit?: number
}

/**
 * Departments updateManyAndReturn
 */
export type DepartmentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * The data used to update Departments.
   */
  data: Prisma.XOR<Prisma.DepartmentsUpdateManyMutationInput, Prisma.DepartmentsUncheckedUpdateManyInput>
  /**
   * Filter which Departments to update
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * Limit how many Departments to update.
   */
  limit?: number
}

/**
 * Departments upsert
 */
export type DepartmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the Departments to update in case it exists.
   */
  where: Prisma.DepartmentsWhereUniqueInput
  /**
   * In case the Departments found by the `where` argument doesn't exist, create a new Departments with this data.
   */
  create: Prisma.XOR<Prisma.DepartmentsCreateInput, Prisma.DepartmentsUncheckedCreateInput>
  /**
   * In case the Departments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DepartmentsUpdateInput, Prisma.DepartmentsUncheckedUpdateInput>
}

/**
 * Departments delete
 */
export type DepartmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
  /**
   * Filter which Departments to delete.
   */
  where: Prisma.DepartmentsWhereUniqueInput
}

/**
 * Departments deleteMany
 */
export type DepartmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Departments to delete
   */
  where?: Prisma.DepartmentsWhereInput
  /**
   * Limit how many Departments to delete.
   */
  limit?: number
}

/**
 * Departments.employees
 */
export type Departments$employeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  where?: Prisma.EmployeesWhereInput
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  cursor?: Prisma.EmployeesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Departments without action
 */
export type DepartmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departments
   */
  select?: Prisma.DepartmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departments
   */
  omit?: Prisma.DepartmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartmentsInclude<ExtArgs> | null
}
