
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Invoices` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Invoices
 * 
 */
export type InvoicesModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoicesPayload>

export type AggregateInvoices = {
  _count: InvoicesCountAggregateOutputType | null
  _avg: InvoicesAvgAggregateOutputType | null
  _sum: InvoicesSumAggregateOutputType | null
  _min: InvoicesMinAggregateOutputType | null
  _max: InvoicesMaxAggregateOutputType | null
}

export type InvoicesAvgAggregateOutputType = {
  id: number | null
  total: number | null
  createdById: number | null
}

export type InvoicesSumAggregateOutputType = {
  id: number | null
  total: number | null
  createdById: number | null
}

export type InvoicesMinAggregateOutputType = {
  id: number | null
  title: string | null
  total: number | null
  status: string | null
  banner: string | null
  updatedAt: Date | null
  createdAt: Date | null
  customerId: string | null
  createdById: number | null
}

export type InvoicesMaxAggregateOutputType = {
  id: number | null
  title: string | null
  total: number | null
  status: string | null
  banner: string | null
  updatedAt: Date | null
  createdAt: Date | null
  customerId: string | null
  createdById: number | null
}

export type InvoicesCountAggregateOutputType = {
  id: number
  title: number
  total: number
  status: number
  banner: number
  updatedAt: number
  createdAt: number
  customerId: number
  createdById: number
  _all: number
}


export type InvoicesAvgAggregateInputType = {
  id?: true
  total?: true
  createdById?: true
}

export type InvoicesSumAggregateInputType = {
  id?: true
  total?: true
  createdById?: true
}

export type InvoicesMinAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  banner?: true
  updatedAt?: true
  createdAt?: true
  customerId?: true
  createdById?: true
}

export type InvoicesMaxAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  banner?: true
  updatedAt?: true
  createdAt?: true
  customerId?: true
  createdById?: true
}

export type InvoicesCountAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  banner?: true
  updatedAt?: true
  createdAt?: true
  customerId?: true
  createdById?: true
  _all?: true
}

export type InvoicesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoices to aggregate.
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoicesOrderByWithRelationInput | Prisma.InvoicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InvoicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Invoices
  **/
  _count?: true | InvoicesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InvoicesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InvoicesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InvoicesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InvoicesMaxAggregateInputType
}

export type GetInvoicesAggregateType<T extends InvoicesAggregateArgs> = {
      [P in keyof T & keyof AggregateInvoices]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInvoices[P]>
    : Prisma.GetScalarType<T[P], AggregateInvoices[P]>
}




export type InvoicesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoicesWhereInput
  orderBy?: Prisma.InvoicesOrderByWithAggregationInput | Prisma.InvoicesOrderByWithAggregationInput[]
  by: Prisma.InvoicesScalarFieldEnum[] | Prisma.InvoicesScalarFieldEnum
  having?: Prisma.InvoicesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InvoicesCountAggregateInputType | true
  _avg?: InvoicesAvgAggregateInputType
  _sum?: InvoicesSumAggregateInputType
  _min?: InvoicesMinAggregateInputType
  _max?: InvoicesMaxAggregateInputType
}

export type InvoicesGroupByOutputType = {
  id: number
  title: string | null
  total: number | null
  status: string | null
  banner: string | null
  updatedAt: Date | null
  createdAt: Date | null
  customerId: string | null
  createdById: number | null
  _count: InvoicesCountAggregateOutputType | null
  _avg: InvoicesAvgAggregateOutputType | null
  _sum: InvoicesSumAggregateOutputType | null
  _min: InvoicesMinAggregateOutputType | null
  _max: InvoicesMaxAggregateOutputType | null
}

type GetInvoicesGroupByPayload<T extends InvoicesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InvoicesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InvoicesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InvoicesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InvoicesGroupByOutputType[P]>
      }
    >
  >



export type InvoicesWhereInput = {
  AND?: Prisma.InvoicesWhereInput | Prisma.InvoicesWhereInput[]
  OR?: Prisma.InvoicesWhereInput[]
  NOT?: Prisma.InvoicesWhereInput | Prisma.InvoicesWhereInput[]
  id?: Prisma.IntFilter<"Invoices"> | number
  title?: Prisma.StringNullableFilter<"Invoices"> | string | null
  total?: Prisma.FloatNullableFilter<"Invoices"> | number | null
  status?: Prisma.StringNullableFilter<"Invoices"> | string | null
  banner?: Prisma.StringNullableFilter<"Invoices"> | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Invoices"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Invoices"> | Date | string | null
  customerId?: Prisma.StringNullableFilter<"Invoices"> | string | null
  createdById?: Prisma.IntNullableFilter<"Invoices"> | number | null
  transactions?: Prisma.TransactionsListRelationFilter
  invoiceViewers?: Prisma.InvoiceViewersListRelationFilter
  invoiceEditors?: Prisma.InvoiceEditorsListRelationFilter
}

export type InvoicesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  banner?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  transactions?: Prisma.TransactionsOrderByRelationAggregateInput
  invoiceViewers?: Prisma.InvoiceViewersOrderByRelationAggregateInput
  invoiceEditors?: Prisma.InvoiceEditorsOrderByRelationAggregateInput
}

export type InvoicesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.InvoicesWhereInput | Prisma.InvoicesWhereInput[]
  OR?: Prisma.InvoicesWhereInput[]
  NOT?: Prisma.InvoicesWhereInput | Prisma.InvoicesWhereInput[]
  title?: Prisma.StringNullableFilter<"Invoices"> | string | null
  total?: Prisma.FloatNullableFilter<"Invoices"> | number | null
  status?: Prisma.StringNullableFilter<"Invoices"> | string | null
  banner?: Prisma.StringNullableFilter<"Invoices"> | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Invoices"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Invoices"> | Date | string | null
  customerId?: Prisma.StringNullableFilter<"Invoices"> | string | null
  createdById?: Prisma.IntNullableFilter<"Invoices"> | number | null
  transactions?: Prisma.TransactionsListRelationFilter
  invoiceViewers?: Prisma.InvoiceViewersListRelationFilter
  invoiceEditors?: Prisma.InvoiceEditorsListRelationFilter
}, "id">

export type InvoicesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  banner?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.InvoicesCountOrderByAggregateInput
  _avg?: Prisma.InvoicesAvgOrderByAggregateInput
  _max?: Prisma.InvoicesMaxOrderByAggregateInput
  _min?: Prisma.InvoicesMinOrderByAggregateInput
  _sum?: Prisma.InvoicesSumOrderByAggregateInput
}

export type InvoicesScalarWhereWithAggregatesInput = {
  AND?: Prisma.InvoicesScalarWhereWithAggregatesInput | Prisma.InvoicesScalarWhereWithAggregatesInput[]
  OR?: Prisma.InvoicesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InvoicesScalarWhereWithAggregatesInput | Prisma.InvoicesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Invoices"> | number
  title?: Prisma.StringNullableWithAggregatesFilter<"Invoices"> | string | null
  total?: Prisma.FloatNullableWithAggregatesFilter<"Invoices"> | number | null
  status?: Prisma.StringNullableWithAggregatesFilter<"Invoices"> | string | null
  banner?: Prisma.StringNullableWithAggregatesFilter<"Invoices"> | string | null
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Invoices"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Invoices"> | Date | string | null
  customerId?: Prisma.StringNullableWithAggregatesFilter<"Invoices"> | string | null
  createdById?: Prisma.IntNullableWithAggregatesFilter<"Invoices"> | number | null
}

export type InvoicesCreateInput = {
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsCreateNestedManyWithoutRecordsInput
  invoiceViewers?: Prisma.InvoiceViewersCreateNestedManyWithoutInvoiceInput
  invoiceEditors?: Prisma.InvoiceEditorsCreateNestedManyWithoutInvoiceInput
}

export type InvoicesUncheckedCreateInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsUncheckedCreateNestedManyWithoutRecordsInput
  invoiceViewers?: Prisma.InvoiceViewersUncheckedCreateNestedManyWithoutInvoiceInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoicesUpdateInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUpdateManyWithoutRecordsNestedInput
  invoiceViewers?: Prisma.InvoiceViewersUpdateManyWithoutInvoiceNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUncheckedUpdateManyWithoutRecordsNestedInput
  invoiceViewers?: Prisma.InvoiceViewersUncheckedUpdateManyWithoutInvoiceNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesCreateManyInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
}

export type InvoicesUpdateManyMutationInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type InvoicesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type InvoicesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type InvoicesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type InvoicesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type InvoicesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  banner?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type InvoicesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type InvoicesScalarRelationFilter = {
  is?: Prisma.InvoicesWhereInput
  isNot?: Prisma.InvoicesWhereInput
}

export type InvoicesNullableScalarRelationFilter = {
  is?: Prisma.InvoicesWhereInput | null
  isNot?: Prisma.InvoicesWhereInput | null
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type InvoicesCreateNestedOneWithoutInvoiceViewersInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceViewersInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutInvoiceViewersInput
  connect?: Prisma.InvoicesWhereUniqueInput
}

export type InvoicesUpdateOneRequiredWithoutInvoiceViewersNestedInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceViewersInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutInvoiceViewersInput
  upsert?: Prisma.InvoicesUpsertWithoutInvoiceViewersInput
  connect?: Prisma.InvoicesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoicesUpdateToOneWithWhereWithoutInvoiceViewersInput, Prisma.InvoicesUpdateWithoutInvoiceViewersInput>, Prisma.InvoicesUncheckedUpdateWithoutInvoiceViewersInput>
}

export type InvoicesCreateNestedOneWithoutInvoiceEditorsInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceEditorsInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutInvoiceEditorsInput
  connect?: Prisma.InvoicesWhereUniqueInput
}

export type InvoicesUpdateOneRequiredWithoutInvoiceEditorsNestedInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceEditorsInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutInvoiceEditorsInput
  upsert?: Prisma.InvoicesUpsertWithoutInvoiceEditorsInput
  connect?: Prisma.InvoicesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoicesUpdateToOneWithWhereWithoutInvoiceEditorsInput, Prisma.InvoicesUpdateWithoutInvoiceEditorsInput>, Prisma.InvoicesUncheckedUpdateWithoutInvoiceEditorsInput>
}

export type InvoicesCreateNestedOneWithoutTransactionsInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutTransactionsInput, Prisma.InvoicesUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutTransactionsInput
  connect?: Prisma.InvoicesWhereUniqueInput
}

export type InvoicesUpdateOneWithoutTransactionsNestedInput = {
  create?: Prisma.XOR<Prisma.InvoicesCreateWithoutTransactionsInput, Prisma.InvoicesUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.InvoicesCreateOrConnectWithoutTransactionsInput
  upsert?: Prisma.InvoicesUpsertWithoutTransactionsInput
  disconnect?: Prisma.InvoicesWhereInput | boolean
  delete?: Prisma.InvoicesWhereInput | boolean
  connect?: Prisma.InvoicesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoicesUpdateToOneWithWhereWithoutTransactionsInput, Prisma.InvoicesUpdateWithoutTransactionsInput>, Prisma.InvoicesUncheckedUpdateWithoutTransactionsInput>
}

export type InvoicesCreateWithoutInvoiceViewersInput = {
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsCreateNestedManyWithoutRecordsInput
  invoiceEditors?: Prisma.InvoiceEditorsCreateNestedManyWithoutInvoiceInput
}

export type InvoicesUncheckedCreateWithoutInvoiceViewersInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsUncheckedCreateNestedManyWithoutRecordsInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoicesCreateOrConnectWithoutInvoiceViewersInput = {
  where: Prisma.InvoicesWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceViewersInput>
}

export type InvoicesUpsertWithoutInvoiceViewersInput = {
  update: Prisma.XOR<Prisma.InvoicesUpdateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedUpdateWithoutInvoiceViewersInput>
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceViewersInput>
  where?: Prisma.InvoicesWhereInput
}

export type InvoicesUpdateToOneWithWhereWithoutInvoiceViewersInput = {
  where?: Prisma.InvoicesWhereInput
  data: Prisma.XOR<Prisma.InvoicesUpdateWithoutInvoiceViewersInput, Prisma.InvoicesUncheckedUpdateWithoutInvoiceViewersInput>
}

export type InvoicesUpdateWithoutInvoiceViewersInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUpdateManyWithoutRecordsNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesUncheckedUpdateWithoutInvoiceViewersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUncheckedUpdateManyWithoutRecordsNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesCreateWithoutInvoiceEditorsInput = {
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsCreateNestedManyWithoutRecordsInput
  invoiceViewers?: Prisma.InvoiceViewersCreateNestedManyWithoutInvoiceInput
}

export type InvoicesUncheckedCreateWithoutInvoiceEditorsInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  transactions?: Prisma.TransactionsUncheckedCreateNestedManyWithoutRecordsInput
  invoiceViewers?: Prisma.InvoiceViewersUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoicesCreateOrConnectWithoutInvoiceEditorsInput = {
  where: Prisma.InvoicesWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceEditorsInput>
}

export type InvoicesUpsertWithoutInvoiceEditorsInput = {
  update: Prisma.XOR<Prisma.InvoicesUpdateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedUpdateWithoutInvoiceEditorsInput>
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedCreateWithoutInvoiceEditorsInput>
  where?: Prisma.InvoicesWhereInput
}

export type InvoicesUpdateToOneWithWhereWithoutInvoiceEditorsInput = {
  where?: Prisma.InvoicesWhereInput
  data: Prisma.XOR<Prisma.InvoicesUpdateWithoutInvoiceEditorsInput, Prisma.InvoicesUncheckedUpdateWithoutInvoiceEditorsInput>
}

export type InvoicesUpdateWithoutInvoiceEditorsInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUpdateManyWithoutRecordsNestedInput
  invoiceViewers?: Prisma.InvoiceViewersUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesUncheckedUpdateWithoutInvoiceEditorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  transactions?: Prisma.TransactionsUncheckedUpdateManyWithoutRecordsNestedInput
  invoiceViewers?: Prisma.InvoiceViewersUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesCreateWithoutTransactionsInput = {
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  invoiceViewers?: Prisma.InvoiceViewersCreateNestedManyWithoutInvoiceInput
  invoiceEditors?: Prisma.InvoiceEditorsCreateNestedManyWithoutInvoiceInput
}

export type InvoicesUncheckedCreateWithoutTransactionsInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: string | null
  banner?: string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  customerId?: string | null
  createdById?: number | null
  invoiceViewers?: Prisma.InvoiceViewersUncheckedCreateNestedManyWithoutInvoiceInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoicesCreateOrConnectWithoutTransactionsInput = {
  where: Prisma.InvoicesWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutTransactionsInput, Prisma.InvoicesUncheckedCreateWithoutTransactionsInput>
}

export type InvoicesUpsertWithoutTransactionsInput = {
  update: Prisma.XOR<Prisma.InvoicesUpdateWithoutTransactionsInput, Prisma.InvoicesUncheckedUpdateWithoutTransactionsInput>
  create: Prisma.XOR<Prisma.InvoicesCreateWithoutTransactionsInput, Prisma.InvoicesUncheckedCreateWithoutTransactionsInput>
  where?: Prisma.InvoicesWhereInput
}

export type InvoicesUpdateToOneWithWhereWithoutTransactionsInput = {
  where?: Prisma.InvoicesWhereInput
  data: Prisma.XOR<Prisma.InvoicesUpdateWithoutTransactionsInput, Prisma.InvoicesUncheckedUpdateWithoutTransactionsInput>
}

export type InvoicesUpdateWithoutTransactionsInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceViewers?: Prisma.InvoiceViewersUpdateManyWithoutInvoiceNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUpdateManyWithoutInvoiceNestedInput
}

export type InvoicesUncheckedUpdateWithoutTransactionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  banner?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceViewers?: Prisma.InvoiceViewersUncheckedUpdateManyWithoutInvoiceNestedInput
  invoiceEditors?: Prisma.InvoiceEditorsUncheckedUpdateManyWithoutInvoiceNestedInput
}


/**
 * Count Type InvoicesCountOutputType
 */

export type InvoicesCountOutputType = {
  transactions: number
  invoiceViewers: number
  invoiceEditors: number
}

export type InvoicesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transactions?: boolean | InvoicesCountOutputTypeCountTransactionsArgs
  invoiceViewers?: boolean | InvoicesCountOutputTypeCountInvoiceViewersArgs
  invoiceEditors?: boolean | InvoicesCountOutputTypeCountInvoiceEditorsArgs
}

/**
 * InvoicesCountOutputType without action
 */
export type InvoicesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoicesCountOutputType
   */
  select?: Prisma.InvoicesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * InvoicesCountOutputType without action
 */
export type InvoicesCountOutputTypeCountTransactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionsWhereInput
}

/**
 * InvoicesCountOutputType without action
 */
export type InvoicesCountOutputTypeCountInvoiceViewersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceViewersWhereInput
}

/**
 * InvoicesCountOutputType without action
 */
export type InvoicesCountOutputTypeCountInvoiceEditorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceEditorsWhereInput
}


export type InvoicesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  banner?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  customerId?: boolean
  createdById?: boolean
  transactions?: boolean | Prisma.Invoices$transactionsArgs<ExtArgs>
  invoiceViewers?: boolean | Prisma.Invoices$invoiceViewersArgs<ExtArgs>
  invoiceEditors?: boolean | Prisma.Invoices$invoiceEditorsArgs<ExtArgs>
  _count?: boolean | Prisma.InvoicesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoices"]>

export type InvoicesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  banner?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  customerId?: boolean
  createdById?: boolean
}, ExtArgs["result"]["invoices"]>

export type InvoicesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  banner?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  customerId?: boolean
  createdById?: boolean
}, ExtArgs["result"]["invoices"]>

export type InvoicesSelectScalar = {
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  banner?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  customerId?: boolean
  createdById?: boolean
}

export type InvoicesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "total" | "status" | "banner" | "updatedAt" | "createdAt" | "customerId" | "createdById", ExtArgs["result"]["invoices"]>
export type InvoicesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transactions?: boolean | Prisma.Invoices$transactionsArgs<ExtArgs>
  invoiceViewers?: boolean | Prisma.Invoices$invoiceViewersArgs<ExtArgs>
  invoiceEditors?: boolean | Prisma.Invoices$invoiceEditorsArgs<ExtArgs>
  _count?: boolean | Prisma.InvoicesCountOutputTypeDefaultArgs<ExtArgs>
}
export type InvoicesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type InvoicesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $InvoicesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Invoices"
  objects: {
    transactions: Prisma.$TransactionsPayload<ExtArgs>[]
    invoiceViewers: Prisma.$InvoiceViewersPayload<ExtArgs>[]
    invoiceEditors: Prisma.$InvoiceEditorsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string | null
    total: number | null
    status: string | null
    banner: string | null
    updatedAt: Date | null
    createdAt: Date | null
    customerId: string | null
    createdById: number | null
  }, ExtArgs["result"]["invoices"]>
  composites: {}
}

export type InvoicesGetPayload<S extends boolean | null | undefined | InvoicesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoicesPayload, S>

export type InvoicesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InvoicesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InvoicesCountAggregateInputType | true
  }

export interface InvoicesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Invoices'], meta: { name: 'Invoices' } }
  /**
   * Find zero or one Invoices that matches the filter.
   * @param {InvoicesFindUniqueArgs} args - Arguments to find a Invoices
   * @example
   * // Get one Invoices
   * const invoices = await prisma.invoices.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InvoicesFindUniqueArgs>(args: Prisma.SelectSubset<T, InvoicesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Invoices that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InvoicesFindUniqueOrThrowArgs} args - Arguments to find a Invoices
   * @example
   * // Get one Invoices
   * const invoices = await prisma.invoices.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InvoicesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InvoicesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesFindFirstArgs} args - Arguments to find a Invoices
   * @example
   * // Get one Invoices
   * const invoices = await prisma.invoices.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InvoicesFindFirstArgs>(args?: Prisma.SelectSubset<T, InvoicesFindFirstArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoices that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesFindFirstOrThrowArgs} args - Arguments to find a Invoices
   * @example
   * // Get one Invoices
   * const invoices = await prisma.invoices.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InvoicesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InvoicesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Invoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Invoices
   * const invoices = await prisma.invoices.findMany()
   * 
   * // Get first 10 Invoices
   * const invoices = await prisma.invoices.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const invoicesWithIdOnly = await prisma.invoices.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InvoicesFindManyArgs>(args?: Prisma.SelectSubset<T, InvoicesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Invoices.
   * @param {InvoicesCreateArgs} args - Arguments to create a Invoices.
   * @example
   * // Create one Invoices
   * const Invoices = await prisma.invoices.create({
   *   data: {
   *     // ... data to create a Invoices
   *   }
   * })
   * 
   */
  create<T extends InvoicesCreateArgs>(args: Prisma.SelectSubset<T, InvoicesCreateArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Invoices.
   * @param {InvoicesCreateManyArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoices = await prisma.invoices.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InvoicesCreateManyArgs>(args?: Prisma.SelectSubset<T, InvoicesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Invoices and returns the data saved in the database.
   * @param {InvoicesCreateManyAndReturnArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoices = await prisma.invoices.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Invoices and only return the `id`
   * const invoicesWithIdOnly = await prisma.invoices.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InvoicesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InvoicesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Invoices.
   * @param {InvoicesDeleteArgs} args - Arguments to delete one Invoices.
   * @example
   * // Delete one Invoices
   * const Invoices = await prisma.invoices.delete({
   *   where: {
   *     // ... filter to delete one Invoices
   *   }
   * })
   * 
   */
  delete<T extends InvoicesDeleteArgs>(args: Prisma.SelectSubset<T, InvoicesDeleteArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Invoices.
   * @param {InvoicesUpdateArgs} args - Arguments to update one Invoices.
   * @example
   * // Update one Invoices
   * const invoices = await prisma.invoices.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InvoicesUpdateArgs>(args: Prisma.SelectSubset<T, InvoicesUpdateArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Invoices.
   * @param {InvoicesDeleteManyArgs} args - Arguments to filter Invoices to delete.
   * @example
   * // Delete a few Invoices
   * const { count } = await prisma.invoices.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InvoicesDeleteManyArgs>(args?: Prisma.SelectSubset<T, InvoicesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Invoices
   * const invoices = await prisma.invoices.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InvoicesUpdateManyArgs>(args: Prisma.SelectSubset<T, InvoicesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices and returns the data updated in the database.
   * @param {InvoicesUpdateManyAndReturnArgs} args - Arguments to update many Invoices.
   * @example
   * // Update many Invoices
   * const invoices = await prisma.invoices.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Invoices and only return the `id`
   * const invoicesWithIdOnly = await prisma.invoices.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InvoicesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InvoicesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Invoices.
   * @param {InvoicesUpsertArgs} args - Arguments to update or create a Invoices.
   * @example
   * // Update or create a Invoices
   * const invoices = await prisma.invoices.upsert({
   *   create: {
   *     // ... data to create a Invoices
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Invoices we want to update
   *   }
   * })
   */
  upsert<T extends InvoicesUpsertArgs>(args: Prisma.SelectSubset<T, InvoicesUpsertArgs<ExtArgs>>): Prisma.Prisma__InvoicesClient<runtime.Types.Result.GetResult<Prisma.$InvoicesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesCountArgs} args - Arguments to filter Invoices to count.
   * @example
   * // Count the number of Invoices
   * const count = await prisma.invoices.count({
   *   where: {
   *     // ... the filter for the Invoices we want to count
   *   }
   * })
  **/
  count<T extends InvoicesCountArgs>(
    args?: Prisma.Subset<T, InvoicesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InvoicesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InvoicesAggregateArgs>(args: Prisma.Subset<T, InvoicesAggregateArgs>): Prisma.PrismaPromise<GetInvoicesAggregateType<T>>

  /**
   * Group by Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoicesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InvoicesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InvoicesGroupByArgs['orderBy'] }
      : { orderBy?: InvoicesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InvoicesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInvoicesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Invoices model
 */
readonly fields: InvoicesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Invoices.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InvoicesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  transactions<T extends Prisma.Invoices$transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoices$transactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  invoiceViewers<T extends Prisma.Invoices$invoiceViewersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoices$invoiceViewersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceViewersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  invoiceEditors<T extends Prisma.Invoices$invoiceEditorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoices$invoiceEditorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceEditorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Invoices model
 */
export interface InvoicesFieldRefs {
  readonly id: Prisma.FieldRef<"Invoices", 'Int'>
  readonly title: Prisma.FieldRef<"Invoices", 'String'>
  readonly total: Prisma.FieldRef<"Invoices", 'Float'>
  readonly status: Prisma.FieldRef<"Invoices", 'String'>
  readonly banner: Prisma.FieldRef<"Invoices", 'String'>
  readonly updatedAt: Prisma.FieldRef<"Invoices", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Invoices", 'DateTime'>
  readonly customerId: Prisma.FieldRef<"Invoices", 'String'>
  readonly createdById: Prisma.FieldRef<"Invoices", 'Int'>
}
    

// Custom InputTypes
/**
 * Invoices findUnique
 */
export type InvoicesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where: Prisma.InvoicesWhereUniqueInput
}

/**
 * Invoices findUniqueOrThrow
 */
export type InvoicesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where: Prisma.InvoicesWhereUniqueInput
}

/**
 * Invoices findFirst
 */
export type InvoicesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoicesOrderByWithRelationInput | Prisma.InvoicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoicesScalarFieldEnum | Prisma.InvoicesScalarFieldEnum[]
}

/**
 * Invoices findFirstOrThrow
 */
export type InvoicesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoicesOrderByWithRelationInput | Prisma.InvoicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoicesScalarFieldEnum | Prisma.InvoicesScalarFieldEnum[]
}

/**
 * Invoices findMany
 */
export type InvoicesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoicesOrderByWithRelationInput | Prisma.InvoicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Invoices.
   */
  cursor?: Prisma.InvoicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  distinct?: Prisma.InvoicesScalarFieldEnum | Prisma.InvoicesScalarFieldEnum[]
}

/**
 * Invoices create
 */
export type InvoicesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * The data needed to create a Invoices.
   */
  data?: Prisma.XOR<Prisma.InvoicesCreateInput, Prisma.InvoicesUncheckedCreateInput>
}

/**
 * Invoices createMany
 */
export type InvoicesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoicesCreateManyInput | Prisma.InvoicesCreateManyInput[]
}

/**
 * Invoices createManyAndReturn
 */
export type InvoicesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoicesCreateManyInput | Prisma.InvoicesCreateManyInput[]
}

/**
 * Invoices update
 */
export type InvoicesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * The data needed to update a Invoices.
   */
  data: Prisma.XOR<Prisma.InvoicesUpdateInput, Prisma.InvoicesUncheckedUpdateInput>
  /**
   * Choose, which Invoices to update.
   */
  where: Prisma.InvoicesWhereUniqueInput
}

/**
 * Invoices updateMany
 */
export type InvoicesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoicesUpdateManyMutationInput, Prisma.InvoicesUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
}

/**
 * Invoices updateManyAndReturn
 */
export type InvoicesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoicesUpdateManyMutationInput, Prisma.InvoicesUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
}

/**
 * Invoices upsert
 */
export type InvoicesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * The filter to search for the Invoices to update in case it exists.
   */
  where: Prisma.InvoicesWhereUniqueInput
  /**
   * In case the Invoices found by the `where` argument doesn't exist, create a new Invoices with this data.
   */
  create: Prisma.XOR<Prisma.InvoicesCreateInput, Prisma.InvoicesUncheckedCreateInput>
  /**
   * In case the Invoices was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InvoicesUpdateInput, Prisma.InvoicesUncheckedUpdateInput>
}

/**
 * Invoices delete
 */
export type InvoicesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
  /**
   * Filter which Invoices to delete.
   */
  where: Prisma.InvoicesWhereUniqueInput
}

/**
 * Invoices deleteMany
 */
export type InvoicesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoices to delete
   */
  where?: Prisma.InvoicesWhereInput
  /**
   * Limit how many Invoices to delete.
   */
  limit?: number
}

/**
 * Invoices.transactions
 */
export type Invoices$transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transactions
   */
  select?: Prisma.TransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transactions
   */
  omit?: Prisma.TransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionsInclude<ExtArgs> | null
  where?: Prisma.TransactionsWhereInput
  orderBy?: Prisma.TransactionsOrderByWithRelationInput | Prisma.TransactionsOrderByWithRelationInput[]
  cursor?: Prisma.TransactionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransactionsScalarFieldEnum | Prisma.TransactionsScalarFieldEnum[]
}

/**
 * Invoices.invoiceViewers
 */
export type Invoices$invoiceViewersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceViewers
   */
  select?: Prisma.InvoiceViewersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceViewers
   */
  omit?: Prisma.InvoiceViewersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceViewersInclude<ExtArgs> | null
  where?: Prisma.InvoiceViewersWhereInput
  orderBy?: Prisma.InvoiceViewersOrderByWithRelationInput | Prisma.InvoiceViewersOrderByWithRelationInput[]
  cursor?: Prisma.InvoiceViewersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvoiceViewersScalarFieldEnum | Prisma.InvoiceViewersScalarFieldEnum[]
}

/**
 * Invoices.invoiceEditors
 */
export type Invoices$invoiceEditorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceEditors
   */
  select?: Prisma.InvoiceEditorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceEditors
   */
  omit?: Prisma.InvoiceEditorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceEditorsInclude<ExtArgs> | null
  where?: Prisma.InvoiceEditorsWhereInput
  orderBy?: Prisma.InvoiceEditorsOrderByWithRelationInput | Prisma.InvoiceEditorsOrderByWithRelationInput[]
  cursor?: Prisma.InvoiceEditorsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvoiceEditorsScalarFieldEnum | Prisma.InvoiceEditorsScalarFieldEnum[]
}

/**
 * Invoices without action
 */
export type InvoicesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoices
   */
  select?: Prisma.InvoicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoices
   */
  omit?: Prisma.InvoicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoicesInclude<ExtArgs> | null
}
