
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Invoice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Invoice
 * 
 */
export type InvoiceModel = runtime.Types.Result.DefaultSelection<Prisma.$InvoicePayload>

export type AggregateInvoice = {
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

export type InvoiceAvgAggregateOutputType = {
  id: number | null
  total: number | null
  createdById: number | null
  customerId: number | null
}

export type InvoiceSumAggregateOutputType = {
  id: number | null
  total: number | null
  createdById: number | null
  customerId: number | null
}

export type InvoiceMinAggregateOutputType = {
  id: number | null
  title: string | null
  total: number | null
  status: $Enums.InvoiceStatus | null
  date: Date | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
  customerId: number | null
}

export type InvoiceMaxAggregateOutputType = {
  id: number | null
  title: string | null
  total: number | null
  status: $Enums.InvoiceStatus | null
  date: Date | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
  customerId: number | null
}

export type InvoiceCountAggregateOutputType = {
  id: number
  title: number
  total: number
  status: number
  date: number
  updatedAt: number
  createdAt: number
  createdById: number
  customerId: number
  _all: number
}


export type InvoiceAvgAggregateInputType = {
  id?: true
  total?: true
  createdById?: true
  customerId?: true
}

export type InvoiceSumAggregateInputType = {
  id?: true
  total?: true
  createdById?: true
  customerId?: true
}

export type InvoiceMinAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  date?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
  customerId?: true
}

export type InvoiceMaxAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  date?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
  customerId?: true
}

export type InvoiceCountAggregateInputType = {
  id?: true
  title?: true
  total?: true
  status?: true
  date?: true
  updatedAt?: true
  createdAt?: true
  createdById?: true
  customerId?: true
  _all?: true
}

export type InvoiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoice to aggregate.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Invoices
  **/
  _count?: true | InvoiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InvoiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InvoiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InvoiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InvoiceMaxAggregateInputType
}

export type GetInvoiceAggregateType<T extends InvoiceAggregateArgs> = {
      [P in keyof T & keyof AggregateInvoice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
    : Prisma.GetScalarType<T[P], AggregateInvoice[P]>
}




export type InvoiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceWhereInput
  orderBy?: Prisma.InvoiceOrderByWithAggregationInput | Prisma.InvoiceOrderByWithAggregationInput[]
  by: Prisma.InvoiceScalarFieldEnum[] | Prisma.InvoiceScalarFieldEnum
  having?: Prisma.InvoiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InvoiceCountAggregateInputType | true
  _avg?: InvoiceAvgAggregateInputType
  _sum?: InvoiceSumAggregateInputType
  _min?: InvoiceMinAggregateInputType
  _max?: InvoiceMaxAggregateInputType
}

export type InvoiceGroupByOutputType = {
  id: number
  title: string | null
  total: number | null
  status: $Enums.InvoiceStatus
  date: Date | null
  updatedAt: Date | null
  createdAt: Date | null
  createdById: number | null
  customerId: number | null
  _count: InvoiceCountAggregateOutputType | null
  _avg: InvoiceAvgAggregateOutputType | null
  _sum: InvoiceSumAggregateOutputType | null
  _min: InvoiceMinAggregateOutputType | null
  _max: InvoiceMaxAggregateOutputType | null
}

type GetInvoiceGroupByPayload<T extends InvoiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InvoiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InvoiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InvoiceGroupByOutputType[P]>
      }
    >
  >



export type InvoiceWhereInput = {
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  id?: Prisma.IntFilter<"Invoice"> | number
  title?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatNullableFilter<"Invoice"> | number | null
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  date?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdById?: Prisma.IntNullableFilter<"Invoice"> | number | null
  customerId?: Prisma.IntNullableFilter<"Invoice"> | number | null
  invoiceItems?: Prisma.InvoiceItemListRelationFilter
  customer?: Prisma.XOR<Prisma.CustomerNullableScalarRelationFilter, Prisma.CustomerWhereInput> | null
}

export type InvoiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  invoiceItems?: Prisma.InvoiceItemOrderByRelationAggregateInput
  customer?: Prisma.CustomerOrderByWithRelationInput
}

export type InvoiceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  OR?: Prisma.InvoiceWhereInput[]
  NOT?: Prisma.InvoiceWhereInput | Prisma.InvoiceWhereInput[]
  title?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatNullableFilter<"Invoice"> | number | null
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  date?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdById?: Prisma.IntNullableFilter<"Invoice"> | number | null
  customerId?: Prisma.IntNullableFilter<"Invoice"> | number | null
  invoiceItems?: Prisma.InvoiceItemListRelationFilter
  customer?: Prisma.XOR<Prisma.CustomerNullableScalarRelationFilter, Prisma.CustomerWhereInput> | null
}, "id">

export type InvoiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  total?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.InvoiceCountOrderByAggregateInput
  _avg?: Prisma.InvoiceAvgOrderByAggregateInput
  _max?: Prisma.InvoiceMaxOrderByAggregateInput
  _min?: Prisma.InvoiceMinOrderByAggregateInput
  _sum?: Prisma.InvoiceSumOrderByAggregateInput
}

export type InvoiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.InvoiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InvoiceScalarWhereWithAggregatesInput | Prisma.InvoiceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Invoice"> | number
  title?: Prisma.StringNullableWithAggregatesFilter<"Invoice"> | string | null
  total?: Prisma.FloatNullableWithAggregatesFilter<"Invoice"> | number | null
  status?: Prisma.EnumInvoiceStatusWithAggregatesFilter<"Invoice"> | $Enums.InvoiceStatus
  date?: Prisma.DateTimeNullableWithAggregatesFilter<"Invoice"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Invoice"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Invoice"> | Date | string | null
  createdById?: Prisma.IntNullableWithAggregatesFilter<"Invoice"> | number | null
  customerId?: Prisma.IntNullableWithAggregatesFilter<"Invoice"> | number | null
}

export type InvoiceCreateInput = {
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  invoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
  customer?: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
}

export type InvoiceUncheckedCreateInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  customerId?: number | null
  invoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUpdateInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
  customer?: Prisma.CustomerUpdateOneWithoutInvoicesNestedInput
}

export type InvoiceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  customerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceCreateManyInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  customerId?: number | null
}

export type InvoiceUpdateManyMutationInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type InvoiceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  customerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type InvoiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  date?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  date?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  total?: Prisma.SortOrder
  status?: Prisma.SortOrder
  date?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  total?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
}

export type InvoiceNullableScalarRelationFilter = {
  is?: Prisma.InvoiceWhereInput | null
  isNot?: Prisma.InvoiceWhereInput | null
}

export type InvoiceListRelationFilter = {
  every?: Prisma.InvoiceWhereInput
  some?: Prisma.InvoiceWhereInput
  none?: Prisma.InvoiceWhereInput
}

export type InvoiceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumInvoiceStatusFieldUpdateOperationsInput = {
  set?: $Enums.InvoiceStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type InvoiceCreateNestedOneWithoutInvoiceItemsInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutInvoiceItemsInput
  connect?: Prisma.InvoiceWhereUniqueInput
}

export type InvoiceUpdateOneWithoutInvoiceItemsNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutInvoiceItemsInput
  upsert?: Prisma.InvoiceUpsertWithoutInvoiceItemsInput
  disconnect?: Prisma.InvoiceWhereInput | boolean
  delete?: Prisma.InvoiceWhereInput | boolean
  connect?: Prisma.InvoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InvoiceUpdateToOneWithWhereWithoutInvoiceItemsInput, Prisma.InvoiceUpdateWithoutInvoiceItemsInput>, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
}

export type InvoiceCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
}

export type InvoiceUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput | Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput> | Prisma.InvoiceCreateWithoutCustomerInput[] | Prisma.InvoiceUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.InvoiceCreateOrConnectWithoutCustomerInput | Prisma.InvoiceCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.InvoiceCreateManyCustomerInputEnvelope
  set?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  disconnect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  delete?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  connect?: Prisma.InvoiceWhereUniqueInput | Prisma.InvoiceWhereUniqueInput[]
  update?: Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput | Prisma.InvoiceUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput | Prisma.InvoiceUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
}

export type InvoiceCreateWithoutInvoiceItemsInput = {
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  customer?: Prisma.CustomerCreateNestedOneWithoutInvoicesInput
}

export type InvoiceUncheckedCreateWithoutInvoiceItemsInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  customerId?: number | null
}

export type InvoiceCreateOrConnectWithoutInvoiceItemsInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
}

export type InvoiceUpsertWithoutInvoiceItemsInput = {
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedCreateWithoutInvoiceItemsInput>
  where?: Prisma.InvoiceWhereInput
}

export type InvoiceUpdateToOneWithWhereWithoutInvoiceItemsInput = {
  where?: Prisma.InvoiceWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutInvoiceItemsInput, Prisma.InvoiceUncheckedUpdateWithoutInvoiceItemsInput>
}

export type InvoiceUpdateWithoutInvoiceItemsInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  customer?: Prisma.CustomerUpdateOneWithoutInvoicesNestedInput
}

export type InvoiceUncheckedUpdateWithoutInvoiceItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  customerId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type InvoiceCreateWithoutCustomerInput = {
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  invoiceItems?: Prisma.InvoiceItemCreateNestedManyWithoutInvoiceInput
}

export type InvoiceUncheckedCreateWithoutCustomerInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
  invoiceItems?: Prisma.InvoiceItemUncheckedCreateNestedManyWithoutInvoiceInput
}

export type InvoiceCreateOrConnectWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput>
}

export type InvoiceCreateManyCustomerInputEnvelope = {
  data: Prisma.InvoiceCreateManyCustomerInput | Prisma.InvoiceCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type InvoiceUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  update: Prisma.XOR<Prisma.InvoiceUpdateWithoutCustomerInput, Prisma.InvoiceUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.InvoiceCreateWithoutCustomerInput, Prisma.InvoiceUncheckedCreateWithoutCustomerInput>
}

export type InvoiceUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.InvoiceWhereUniqueInput
  data: Prisma.XOR<Prisma.InvoiceUpdateWithoutCustomerInput, Prisma.InvoiceUncheckedUpdateWithoutCustomerInput>
}

export type InvoiceUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.InvoiceScalarWhereInput
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyWithoutCustomerInput>
}

export type InvoiceScalarWhereInput = {
  AND?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  OR?: Prisma.InvoiceScalarWhereInput[]
  NOT?: Prisma.InvoiceScalarWhereInput | Prisma.InvoiceScalarWhereInput[]
  id?: Prisma.IntFilter<"Invoice"> | number
  title?: Prisma.StringNullableFilter<"Invoice"> | string | null
  total?: Prisma.FloatNullableFilter<"Invoice"> | number | null
  status?: Prisma.EnumInvoiceStatusFilter<"Invoice"> | $Enums.InvoiceStatus
  date?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  updatedAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdAt?: Prisma.DateTimeNullableFilter<"Invoice"> | Date | string | null
  createdById?: Prisma.IntNullableFilter<"Invoice"> | number | null
  customerId?: Prisma.IntNullableFilter<"Invoice"> | number | null
}

export type InvoiceCreateManyCustomerInput = {
  id?: number
  title?: string | null
  total?: number | null
  status?: $Enums.InvoiceStatus
  date?: Date | string | null
  updatedAt?: Date | string | null
  createdAt?: Date | string | null
  createdById?: number | null
}

export type InvoiceUpdateWithoutCustomerInput = {
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceItems?: Prisma.InvoiceItemUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  invoiceItems?: Prisma.InvoiceItemUncheckedUpdateManyWithoutInvoiceNestedInput
}

export type InvoiceUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  total?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  status?: Prisma.EnumInvoiceStatusFieldUpdateOperationsInput | $Enums.InvoiceStatus
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdById?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type InvoiceCountOutputType
 */

export type InvoiceCountOutputType = {
  invoiceItems: number
}

export type InvoiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invoiceItems?: boolean | InvoiceCountOutputTypeCountInvoiceItemsArgs
}

/**
 * InvoiceCountOutputType without action
 */
export type InvoiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceCountOutputType
   */
  select?: Prisma.InvoiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * InvoiceCountOutputType without action
 */
export type InvoiceCountOutputTypeCountInvoiceItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvoiceItemWhereInput
}


export type InvoiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  date?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  customerId?: boolean
  invoiceItems?: boolean | Prisma.Invoice$invoiceItemsArgs<ExtArgs>
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  date?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  customerId?: boolean
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  date?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  customerId?: boolean
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
}, ExtArgs["result"]["invoice"]>

export type InvoiceSelectScalar = {
  id?: boolean
  title?: boolean
  total?: boolean
  status?: boolean
  date?: boolean
  updatedAt?: boolean
  createdAt?: boolean
  createdById?: boolean
  customerId?: boolean
}

export type InvoiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "total" | "status" | "date" | "updatedAt" | "createdAt" | "createdById" | "customerId", ExtArgs["result"]["invoice"]>
export type InvoiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invoiceItems?: boolean | Prisma.Invoice$invoiceItemsArgs<ExtArgs>
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
  _count?: boolean | Prisma.InvoiceCountOutputTypeDefaultArgs<ExtArgs>
}
export type InvoiceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
}
export type InvoiceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.Invoice$customerArgs<ExtArgs>
}

export type $InvoicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Invoice"
  objects: {
    invoiceItems: Prisma.$InvoiceItemPayload<ExtArgs>[]
    customer: Prisma.$CustomerPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string | null
    total: number | null
    status: $Enums.InvoiceStatus
    date: Date | null
    updatedAt: Date | null
    createdAt: Date | null
    createdById: number | null
    customerId: number | null
  }, ExtArgs["result"]["invoice"]>
  composites: {}
}

export type InvoiceGetPayload<S extends boolean | null | undefined | InvoiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InvoicePayload, S>

export type InvoiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InvoiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InvoiceCountAggregateInputType | true
  }

export interface InvoiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Invoice'], meta: { name: 'Invoice' } }
  /**
   * Find zero or one Invoice that matches the filter.
   * @param {InvoiceFindUniqueArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InvoiceFindUniqueArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Invoice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InvoiceFindUniqueOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InvoiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InvoiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InvoiceFindFirstArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Invoice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindFirstOrThrowArgs} args - Arguments to find a Invoice
   * @example
   * // Get one Invoice
   * const invoice = await prisma.invoice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InvoiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InvoiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Invoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Invoices
   * const invoices = await prisma.invoice.findMany()
   * 
   * // Get first 10 Invoices
   * const invoices = await prisma.invoice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const invoiceWithIdOnly = await prisma.invoice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InvoiceFindManyArgs>(args?: Prisma.SelectSubset<T, InvoiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Invoice.
   * @param {InvoiceCreateArgs} args - Arguments to create a Invoice.
   * @example
   * // Create one Invoice
   * const Invoice = await prisma.invoice.create({
   *   data: {
   *     // ... data to create a Invoice
   *   }
   * })
   * 
   */
  create<T extends InvoiceCreateArgs>(args: Prisma.SelectSubset<T, InvoiceCreateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Invoices.
   * @param {InvoiceCreateManyArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoice = await prisma.invoice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InvoiceCreateManyArgs>(args?: Prisma.SelectSubset<T, InvoiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Invoices and returns the data saved in the database.
   * @param {InvoiceCreateManyAndReturnArgs} args - Arguments to create many Invoices.
   * @example
   * // Create many Invoices
   * const invoice = await prisma.invoice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Invoices and only return the `id`
   * const invoiceWithIdOnly = await prisma.invoice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InvoiceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InvoiceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Invoice.
   * @param {InvoiceDeleteArgs} args - Arguments to delete one Invoice.
   * @example
   * // Delete one Invoice
   * const Invoice = await prisma.invoice.delete({
   *   where: {
   *     // ... filter to delete one Invoice
   *   }
   * })
   * 
   */
  delete<T extends InvoiceDeleteArgs>(args: Prisma.SelectSubset<T, InvoiceDeleteArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Invoice.
   * @param {InvoiceUpdateArgs} args - Arguments to update one Invoice.
   * @example
   * // Update one Invoice
   * const invoice = await prisma.invoice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InvoiceUpdateArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Invoices.
   * @param {InvoiceDeleteManyArgs} args - Arguments to filter Invoices to delete.
   * @example
   * // Delete a few Invoices
   * const { count } = await prisma.invoice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InvoiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, InvoiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Invoices
   * const invoice = await prisma.invoice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InvoiceUpdateManyArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Invoices and returns the data updated in the database.
   * @param {InvoiceUpdateManyAndReturnArgs} args - Arguments to update many Invoices.
   * @example
   * // Update many Invoices
   * const invoice = await prisma.invoice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Invoices and only return the `id`
   * const invoiceWithIdOnly = await prisma.invoice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InvoiceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InvoiceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Invoice.
   * @param {InvoiceUpsertArgs} args - Arguments to update or create a Invoice.
   * @example
   * // Update or create a Invoice
   * const invoice = await prisma.invoice.upsert({
   *   create: {
   *     // ... data to create a Invoice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Invoice we want to update
   *   }
   * })
   */
  upsert<T extends InvoiceUpsertArgs>(args: Prisma.SelectSubset<T, InvoiceUpsertArgs<ExtArgs>>): Prisma.Prisma__InvoiceClient<runtime.Types.Result.GetResult<Prisma.$InvoicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Invoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceCountArgs} args - Arguments to filter Invoices to count.
   * @example
   * // Count the number of Invoices
   * const count = await prisma.invoice.count({
   *   where: {
   *     // ... the filter for the Invoices we want to count
   *   }
   * })
  **/
  count<T extends InvoiceCountArgs>(
    args?: Prisma.Subset<T, InvoiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InvoiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InvoiceAggregateArgs>(args: Prisma.Subset<T, InvoiceAggregateArgs>): Prisma.PrismaPromise<GetInvoiceAggregateType<T>>

  /**
   * Group by Invoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InvoiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InvoiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InvoiceGroupByArgs['orderBy'] }
      : { orderBy?: InvoiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InvoiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInvoiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Invoice model
 */
readonly fields: InvoiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Invoice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InvoiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  invoiceItems<T extends Prisma.Invoice$invoiceItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoice$invoiceItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvoiceItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  customer<T extends Prisma.Invoice$customerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Invoice$customerArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Invoice model
 */
export interface InvoiceFieldRefs {
  readonly id: Prisma.FieldRef<"Invoice", 'Int'>
  readonly title: Prisma.FieldRef<"Invoice", 'String'>
  readonly total: Prisma.FieldRef<"Invoice", 'Float'>
  readonly status: Prisma.FieldRef<"Invoice", 'InvoiceStatus'>
  readonly date: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Invoice", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"Invoice", 'Int'>
  readonly customerId: Prisma.FieldRef<"Invoice", 'Int'>
}
    

// Custom InputTypes
/**
 * Invoice findUnique
 */
export type InvoiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findUniqueOrThrow
 */
export type InvoiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice findFirst
 */
export type InvoiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findFirstOrThrow
 */
export type InvoiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoice to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Invoices.
   */
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice findMany
 */
export type InvoiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter, which Invoices to fetch.
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Invoices to fetch.
   */
  orderBy?: Prisma.InvoiceOrderByWithRelationInput | Prisma.InvoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Invoices.
   */
  cursor?: Prisma.InvoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Invoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Invoices.
   */
  skip?: number
  distinct?: Prisma.InvoiceScalarFieldEnum | Prisma.InvoiceScalarFieldEnum[]
}

/**
 * Invoice create
 */
export type InvoiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to create a Invoice.
   */
  data?: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
}

/**
 * Invoice createMany
 */
export type InvoiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoiceCreateManyInput | Prisma.InvoiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Invoice createManyAndReturn
 */
export type InvoiceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * The data used to create many Invoices.
   */
  data: Prisma.InvoiceCreateManyInput | Prisma.InvoiceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Invoice update
 */
export type InvoiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The data needed to update a Invoice.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
  /**
   * Choose, which Invoice to update.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice updateMany
 */
export type InvoiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
}

/**
 * Invoice updateManyAndReturn
 */
export type InvoiceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * The data used to update Invoices.
   */
  data: Prisma.XOR<Prisma.InvoiceUpdateManyMutationInput, Prisma.InvoiceUncheckedUpdateManyInput>
  /**
   * Filter which Invoices to update
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Invoice upsert
 */
export type InvoiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * The filter to search for the Invoice to update in case it exists.
   */
  where: Prisma.InvoiceWhereUniqueInput
  /**
   * In case the Invoice found by the `where` argument doesn't exist, create a new Invoice with this data.
   */
  create: Prisma.XOR<Prisma.InvoiceCreateInput, Prisma.InvoiceUncheckedCreateInput>
  /**
   * In case the Invoice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InvoiceUpdateInput, Prisma.InvoiceUncheckedUpdateInput>
}

/**
 * Invoice delete
 */
export type InvoiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
  /**
   * Filter which Invoice to delete.
   */
  where: Prisma.InvoiceWhereUniqueInput
}

/**
 * Invoice deleteMany
 */
export type InvoiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Invoices to delete
   */
  where?: Prisma.InvoiceWhereInput
  /**
   * Limit how many Invoices to delete.
   */
  limit?: number
}

/**
 * Invoice.invoiceItems
 */
export type Invoice$invoiceItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InvoiceItem
   */
  select?: Prisma.InvoiceItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InvoiceItem
   */
  omit?: Prisma.InvoiceItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceItemInclude<ExtArgs> | null
  where?: Prisma.InvoiceItemWhereInput
  orderBy?: Prisma.InvoiceItemOrderByWithRelationInput | Prisma.InvoiceItemOrderByWithRelationInput[]
  cursor?: Prisma.InvoiceItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvoiceItemScalarFieldEnum | Prisma.InvoiceItemScalarFieldEnum[]
}

/**
 * Invoice.customer
 */
export type Invoice$customerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  where?: Prisma.CustomerWhereInput
}

/**
 * Invoice without action
 */
export type InvoiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invoice
   */
  select?: Prisma.InvoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invoice
   */
  omit?: Prisma.InvoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvoiceInclude<ExtArgs> | null
}
