import {
  InventoryItem,
  Invoice,
  InvoiceLine,
  InvoiceGroup,
} from '@/types/generics';

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    sku: 'SKU-001',
    name: 'Web Development Service',
    description: 'Professional web development hourly rate',
    unitPrice: 150,
    unit: 'hour',
    category: 'Services',
    inStock: 999,
  },
  {
    id: '2',
    sku: 'SKU-002',
    name: 'UI/UX Design',
    description: 'User interface and experience design',
    unitPrice: 120,
    unit: 'hour',
    category: 'Services',
    inStock: 999,
  },
  {
    id: '3',
    sku: 'SKU-003',
    name: 'Domain Registration',
    description: 'Annual domain name registration',
    unitPrice: 15,
    unit: 'year',
    category: 'Products',
    inStock: 50,
  },
  {
    id: '4',
    sku: 'SKU-004',
    name: 'Web Hosting - Basic',
    description: 'Basic shared hosting plan (monthly)',
    unitPrice: 9.99,
    unit: 'month',
    category: 'Products',
    inStock: 100,
  },
  {
    id: '5',
    sku: 'SKU-005',
    name: 'Web Hosting - Premium',
    description: 'Premium VPS hosting plan (monthly)',
    unitPrice: 49.99,
    unit: 'month',
    category: 'Products',
    inStock: 50,
  },
  {
    id: '6',
    sku: 'SKU-006',
    name: 'SSL Certificate',
    description: 'Annual SSL certificate',
    unitPrice: 79,
    unit: 'year',
    category: 'Products',
    inStock: 200,
  },
  {
    id: '7',
    sku: 'SKU-007',
    name: 'SEO Optimization',
    description: 'Search engine optimization service',
    unitPrice: 500,
    unit: 'project',
    category: 'Services',
    inStock: 999,
  },
  {
    id: '8',
    sku: 'SKU-008',
    name: 'Content Writing',
    description: 'Professional content writing per page',
    unitPrice: 75,
    unit: 'page',
    category: 'Services',
    inStock: 999,
  },
  {
    id: '9',
    sku: 'SKU-009',
    name: 'Logo Design',
    description: 'Custom logo design package',
    unitPrice: 350,
    unit: 'package',
    category: 'Services',
    inStock: 999,
  },
  {
    id: '10',
    sku: 'SKU-010',
    name: 'Email Marketing Setup',
    description: 'Email marketing platform setup and configuration',
    unitPrice: 250,
    unit: 'setup',
    category: 'Services',
    inStock: 999,
  },
];

export const mockInvoice: Invoice = {
  id: 'INV-001',
  invoiceNumber: 'INV-2026-0001',
  customer: {
    id: 'CUST-001',
    name: 'Acme Corporation',
    email: 'billing@acme.com',
    address: '123 Business Ave, Suite 100, New York, NY 10001',
  },
  issueDate: '2026-03-16',
  dueDate: '2026-04-16',
  status: 'draft',
  items: [],
  subtotal: 0,
  taxTotal: 0,
  discountTotal: 0,
  total: 0,
  notes: '',
};

export function createInvoiceLine(
  item: InventoryItem,
  quantity: number = 1,
): InvoiceLine {
  const subtotal = item.unitPrice * quantity;
  return {
    id: `line-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'line',
    itemId: item.id,
    itemName: item.name,
    sku: item.sku,
    description: item.description,
    quantity,
    unitPrice: item.unitPrice,
    discount: 0,
    tax: 0,
    total: subtotal,
  };
}

export function createInvoiceGroup(name: string): InvoiceGroup {
  return {
    id: `group-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type: 'group',
    name,
    description: '',
    lines: [],
    subtotal: 0,
    expanded: true,
  };
}
