
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.1.0
 * Query Engine version: ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba
 */
export const prismaVersion: PrismaVersion = {
  client: "7.1.0",
  engine: "ab635e6b9d606fa5c8fb8b1a7f909c3c3c1c98ba"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Users: 'Users',
  Tokens: 'Tokens',
  Companies: 'Companies',
  Invoices: 'Invoices',
  InvoiceViewers: 'InvoiceViewers',
  InvoiceEditors: 'InvoiceEditors',
  TransactionCategories: 'TransactionCategories',
  Transactions: 'Transactions',
  Records: 'Records',
  Stocks: 'Stocks',
  Assets: 'Assets',
  Departments: 'Departments',
  Employees: 'Employees',
  Suppliers: 'Suppliers',
  Notifications: 'Notifications'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "users" | "tokens" | "companies" | "invoices" | "invoiceViewers" | "invoiceEditors" | "transactionCategories" | "transactions" | "records" | "stocks" | "assets" | "departments" | "employees" | "suppliers" | "notifications"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Users: {
      payload: Prisma.$UsersPayload<ExtArgs>
      fields: Prisma.UsersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findFirst: {
          args: Prisma.UsersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findMany: {
          args: Prisma.UsersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        create: {
          args: Prisma.UsersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        createMany: {
          args: Prisma.UsersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UsersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        delete: {
          args: Prisma.UsersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        update: {
          args: Prisma.UsersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        deleteMany: {
          args: Prisma.UsersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UsersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        upsert: {
          args: Prisma.UsersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.UsersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
    Tokens: {
      payload: Prisma.$TokensPayload<ExtArgs>
      fields: Prisma.TokensFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TokensFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TokensFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        findFirst: {
          args: Prisma.TokensFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TokensFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        findMany: {
          args: Prisma.TokensFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>[]
        }
        create: {
          args: Prisma.TokensCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        createMany: {
          args: Prisma.TokensCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TokensCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>[]
        }
        delete: {
          args: Prisma.TokensDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        update: {
          args: Prisma.TokensUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        deleteMany: {
          args: Prisma.TokensDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TokensUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TokensUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>[]
        }
        upsert: {
          args: Prisma.TokensUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TokensPayload>
        }
        aggregate: {
          args: Prisma.TokensAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTokens>
        }
        groupBy: {
          args: Prisma.TokensGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokensGroupByOutputType>[]
        }
        count: {
          args: Prisma.TokensCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TokensCountAggregateOutputType> | number
        }
      }
    }
    Companies: {
      payload: Prisma.$CompaniesPayload<ExtArgs>
      fields: Prisma.CompaniesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CompaniesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CompaniesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        findFirst: {
          args: Prisma.CompaniesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CompaniesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        findMany: {
          args: Prisma.CompaniesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        create: {
          args: Prisma.CompaniesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        createMany: {
          args: Prisma.CompaniesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CompaniesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        delete: {
          args: Prisma.CompaniesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        update: {
          args: Prisma.CompaniesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        deleteMany: {
          args: Prisma.CompaniesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CompaniesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CompaniesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>[]
        }
        upsert: {
          args: Prisma.CompaniesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompaniesPayload>
        }
        aggregate: {
          args: Prisma.CompaniesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCompanies>
        }
        groupBy: {
          args: Prisma.CompaniesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompaniesGroupByOutputType>[]
        }
        count: {
          args: Prisma.CompaniesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompaniesCountAggregateOutputType> | number
        }
      }
    }
    Invoices: {
      payload: Prisma.$InvoicesPayload<ExtArgs>
      fields: Prisma.InvoicesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InvoicesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InvoicesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        findFirst: {
          args: Prisma.InvoicesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InvoicesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        findMany: {
          args: Prisma.InvoicesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>[]
        }
        create: {
          args: Prisma.InvoicesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        createMany: {
          args: Prisma.InvoicesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InvoicesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>[]
        }
        delete: {
          args: Prisma.InvoicesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        update: {
          args: Prisma.InvoicesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        deleteMany: {
          args: Prisma.InvoicesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InvoicesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InvoicesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>[]
        }
        upsert: {
          args: Prisma.InvoicesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoicesPayload>
        }
        aggregate: {
          args: Prisma.InvoicesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInvoices>
        }
        groupBy: {
          args: Prisma.InvoicesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoicesGroupByOutputType>[]
        }
        count: {
          args: Prisma.InvoicesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoicesCountAggregateOutputType> | number
        }
      }
    }
    InvoiceViewers: {
      payload: Prisma.$InvoiceViewersPayload<ExtArgs>
      fields: Prisma.InvoiceViewersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InvoiceViewersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InvoiceViewersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        findFirst: {
          args: Prisma.InvoiceViewersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InvoiceViewersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        findMany: {
          args: Prisma.InvoiceViewersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>[]
        }
        create: {
          args: Prisma.InvoiceViewersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        createMany: {
          args: Prisma.InvoiceViewersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InvoiceViewersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>[]
        }
        delete: {
          args: Prisma.InvoiceViewersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        update: {
          args: Prisma.InvoiceViewersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        deleteMany: {
          args: Prisma.InvoiceViewersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InvoiceViewersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InvoiceViewersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>[]
        }
        upsert: {
          args: Prisma.InvoiceViewersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceViewersPayload>
        }
        aggregate: {
          args: Prisma.InvoiceViewersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInvoiceViewers>
        }
        groupBy: {
          args: Prisma.InvoiceViewersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoiceViewersGroupByOutputType>[]
        }
        count: {
          args: Prisma.InvoiceViewersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoiceViewersCountAggregateOutputType> | number
        }
      }
    }
    InvoiceEditors: {
      payload: Prisma.$InvoiceEditorsPayload<ExtArgs>
      fields: Prisma.InvoiceEditorsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InvoiceEditorsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InvoiceEditorsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        findFirst: {
          args: Prisma.InvoiceEditorsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InvoiceEditorsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        findMany: {
          args: Prisma.InvoiceEditorsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>[]
        }
        create: {
          args: Prisma.InvoiceEditorsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        createMany: {
          args: Prisma.InvoiceEditorsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.InvoiceEditorsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>[]
        }
        delete: {
          args: Prisma.InvoiceEditorsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        update: {
          args: Prisma.InvoiceEditorsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        deleteMany: {
          args: Prisma.InvoiceEditorsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InvoiceEditorsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.InvoiceEditorsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>[]
        }
        upsert: {
          args: Prisma.InvoiceEditorsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InvoiceEditorsPayload>
        }
        aggregate: {
          args: Prisma.InvoiceEditorsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInvoiceEditors>
        }
        groupBy: {
          args: Prisma.InvoiceEditorsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoiceEditorsGroupByOutputType>[]
        }
        count: {
          args: Prisma.InvoiceEditorsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InvoiceEditorsCountAggregateOutputType> | number
        }
      }
    }
    TransactionCategories: {
      payload: Prisma.$TransactionCategoriesPayload<ExtArgs>
      fields: Prisma.TransactionCategoriesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TransactionCategoriesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TransactionCategoriesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        findFirst: {
          args: Prisma.TransactionCategoriesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TransactionCategoriesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        findMany: {
          args: Prisma.TransactionCategoriesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>[]
        }
        create: {
          args: Prisma.TransactionCategoriesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        createMany: {
          args: Prisma.TransactionCategoriesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TransactionCategoriesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>[]
        }
        delete: {
          args: Prisma.TransactionCategoriesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        update: {
          args: Prisma.TransactionCategoriesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        deleteMany: {
          args: Prisma.TransactionCategoriesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TransactionCategoriesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TransactionCategoriesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>[]
        }
        upsert: {
          args: Prisma.TransactionCategoriesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionCategoriesPayload>
        }
        aggregate: {
          args: Prisma.TransactionCategoriesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTransactionCategories>
        }
        groupBy: {
          args: Prisma.TransactionCategoriesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransactionCategoriesGroupByOutputType>[]
        }
        count: {
          args: Prisma.TransactionCategoriesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransactionCategoriesCountAggregateOutputType> | number
        }
      }
    }
    Transactions: {
      payload: Prisma.$TransactionsPayload<ExtArgs>
      fields: Prisma.TransactionsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TransactionsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TransactionsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        findFirst: {
          args: Prisma.TransactionsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TransactionsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        findMany: {
          args: Prisma.TransactionsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>[]
        }
        create: {
          args: Prisma.TransactionsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        createMany: {
          args: Prisma.TransactionsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TransactionsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>[]
        }
        delete: {
          args: Prisma.TransactionsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        update: {
          args: Prisma.TransactionsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        deleteMany: {
          args: Prisma.TransactionsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TransactionsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TransactionsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>[]
        }
        upsert: {
          args: Prisma.TransactionsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransactionsPayload>
        }
        aggregate: {
          args: Prisma.TransactionsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTransactions>
        }
        groupBy: {
          args: Prisma.TransactionsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransactionsGroupByOutputType>[]
        }
        count: {
          args: Prisma.TransactionsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransactionsCountAggregateOutputType> | number
        }
      }
    }
    Records: {
      payload: Prisma.$RecordsPayload<ExtArgs>
      fields: Prisma.RecordsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecordsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecordsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        findFirst: {
          args: Prisma.RecordsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecordsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        findMany: {
          args: Prisma.RecordsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>[]
        }
        create: {
          args: Prisma.RecordsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        createMany: {
          args: Prisma.RecordsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecordsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>[]
        }
        delete: {
          args: Prisma.RecordsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        update: {
          args: Prisma.RecordsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        deleteMany: {
          args: Prisma.RecordsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecordsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecordsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>[]
        }
        upsert: {
          args: Prisma.RecordsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecordsPayload>
        }
        aggregate: {
          args: Prisma.RecordsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecords>
        }
        groupBy: {
          args: Prisma.RecordsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecordsGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecordsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecordsCountAggregateOutputType> | number
        }
      }
    }
    Stocks: {
      payload: Prisma.$StocksPayload<ExtArgs>
      fields: Prisma.StocksFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StocksFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StocksFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        findFirst: {
          args: Prisma.StocksFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StocksFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        findMany: {
          args: Prisma.StocksFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>[]
        }
        create: {
          args: Prisma.StocksCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        createMany: {
          args: Prisma.StocksCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StocksCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>[]
        }
        delete: {
          args: Prisma.StocksDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        update: {
          args: Prisma.StocksUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        deleteMany: {
          args: Prisma.StocksDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StocksUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StocksUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>[]
        }
        upsert: {
          args: Prisma.StocksUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StocksPayload>
        }
        aggregate: {
          args: Prisma.StocksAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStocks>
        }
        groupBy: {
          args: Prisma.StocksGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StocksGroupByOutputType>[]
        }
        count: {
          args: Prisma.StocksCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StocksCountAggregateOutputType> | number
        }
      }
    }
    Assets: {
      payload: Prisma.$AssetsPayload<ExtArgs>
      fields: Prisma.AssetsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssetsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssetsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        findFirst: {
          args: Prisma.AssetsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssetsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        findMany: {
          args: Prisma.AssetsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>[]
        }
        create: {
          args: Prisma.AssetsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        createMany: {
          args: Prisma.AssetsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssetsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>[]
        }
        delete: {
          args: Prisma.AssetsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        update: {
          args: Prisma.AssetsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        deleteMany: {
          args: Prisma.AssetsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssetsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssetsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>[]
        }
        upsert: {
          args: Prisma.AssetsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetsPayload>
        }
        aggregate: {
          args: Prisma.AssetsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAssets>
        }
        groupBy: {
          args: Prisma.AssetsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssetsGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssetsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssetsCountAggregateOutputType> | number
        }
      }
    }
    Departments: {
      payload: Prisma.$DepartmentsPayload<ExtArgs>
      fields: Prisma.DepartmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DepartmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DepartmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        findFirst: {
          args: Prisma.DepartmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DepartmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        findMany: {
          args: Prisma.DepartmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>[]
        }
        create: {
          args: Prisma.DepartmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        createMany: {
          args: Prisma.DepartmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DepartmentsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>[]
        }
        delete: {
          args: Prisma.DepartmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        update: {
          args: Prisma.DepartmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        deleteMany: {
          args: Prisma.DepartmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DepartmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DepartmentsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>[]
        }
        upsert: {
          args: Prisma.DepartmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartmentsPayload>
        }
        aggregate: {
          args: Prisma.DepartmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartments>
        }
        groupBy: {
          args: Prisma.DepartmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.DepartmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsCountAggregateOutputType> | number
        }
      }
    }
    Employees: {
      payload: Prisma.$EmployeesPayload<ExtArgs>
      fields: Prisma.EmployeesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EmployeesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EmployeesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        findFirst: {
          args: Prisma.EmployeesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EmployeesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        findMany: {
          args: Prisma.EmployeesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>[]
        }
        create: {
          args: Prisma.EmployeesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        createMany: {
          args: Prisma.EmployeesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EmployeesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>[]
        }
        delete: {
          args: Prisma.EmployeesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        update: {
          args: Prisma.EmployeesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        deleteMany: {
          args: Prisma.EmployeesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EmployeesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EmployeesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>[]
        }
        upsert: {
          args: Prisma.EmployeesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmployeesPayload>
        }
        aggregate: {
          args: Prisma.EmployeesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEmployees>
        }
        groupBy: {
          args: Prisma.EmployeesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmployeesGroupByOutputType>[]
        }
        count: {
          args: Prisma.EmployeesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmployeesCountAggregateOutputType> | number
        }
      }
    }
    Suppliers: {
      payload: Prisma.$SuppliersPayload<ExtArgs>
      fields: Prisma.SuppliersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SuppliersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SuppliersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        findFirst: {
          args: Prisma.SuppliersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SuppliersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        findMany: {
          args: Prisma.SuppliersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>[]
        }
        create: {
          args: Prisma.SuppliersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        createMany: {
          args: Prisma.SuppliersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SuppliersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>[]
        }
        delete: {
          args: Prisma.SuppliersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        update: {
          args: Prisma.SuppliersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        deleteMany: {
          args: Prisma.SuppliersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SuppliersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SuppliersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>[]
        }
        upsert: {
          args: Prisma.SuppliersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SuppliersPayload>
        }
        aggregate: {
          args: Prisma.SuppliersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSuppliers>
        }
        groupBy: {
          args: Prisma.SuppliersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SuppliersGroupByOutputType>[]
        }
        count: {
          args: Prisma.SuppliersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SuppliersCountAggregateOutputType> | number
        }
      }
    }
    Notifications: {
      payload: Prisma.$NotificationsPayload<ExtArgs>
      fields: Prisma.NotificationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        findFirst: {
          args: Prisma.NotificationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        findMany: {
          args: Prisma.NotificationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>[]
        }
        create: {
          args: Prisma.NotificationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        createMany: {
          args: Prisma.NotificationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>[]
        }
        delete: {
          args: Prisma.NotificationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        update: {
          args: Prisma.NotificationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        deleteMany: {
          args: Prisma.NotificationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>[]
        }
        upsert: {
          args: Prisma.NotificationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationsPayload>
        }
        aggregate: {
          args: Prisma.NotificationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotifications>
        }
        groupBy: {
          args: Prisma.NotificationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsersScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  locale: 'locale',
  hashedPassword: 'hashedPassword'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const TokensScalarFieldEnum = {
  id: 'id',
  type: 'type',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
} as const

export type TokensScalarFieldEnum = (typeof TokensScalarFieldEnum)[keyof typeof TokensScalarFieldEnum]


export const CompaniesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  telephone: 'telephone',
  logo: 'logo',
  email: 'email',
  defaultCurrency: 'defaultCurrency'
} as const

export type CompaniesScalarFieldEnum = (typeof CompaniesScalarFieldEnum)[keyof typeof CompaniesScalarFieldEnum]


export const InvoicesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  total: 'total',
  status: 'status',
  banner: 'banner',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt',
  customerId: 'customerId',
  createdById: 'createdById'
} as const

export type InvoicesScalarFieldEnum = (typeof InvoicesScalarFieldEnum)[keyof typeof InvoicesScalarFieldEnum]


export const InvoiceViewersScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type InvoiceViewersScalarFieldEnum = (typeof InvoiceViewersScalarFieldEnum)[keyof typeof InvoiceViewersScalarFieldEnum]


export const InvoiceEditorsScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type InvoiceEditorsScalarFieldEnum = (typeof InvoiceEditorsScalarFieldEnum)[keyof typeof InvoiceEditorsScalarFieldEnum]


export const TransactionCategoriesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  transactionId: 'transactionId'
} as const

export type TransactionCategoriesScalarFieldEnum = (typeof TransactionCategoriesScalarFieldEnum)[keyof typeof TransactionCategoriesScalarFieldEnum]


export const TransactionsScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  description: 'description',
  date: 'date',
  qty: 'qty',
  tax: 'tax',
  noteId: 'noteId',
  recordsId: 'recordsId',
  transactionCategoriesId: 'transactionCategoriesId'
} as const

export type TransactionsScalarFieldEnum = (typeof TransactionsScalarFieldEnum)[keyof typeof TransactionsScalarFieldEnum]


export const RecordsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  code: 'code',
  image: 'image',
  status: 'status',
  phone: 'phone',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedBy: 'deletedBy'
} as const

export type RecordsScalarFieldEnum = (typeof RecordsScalarFieldEnum)[keyof typeof RecordsScalarFieldEnum]


export const StocksScalarFieldEnum = {
  id: 'id',
  name: 'name',
  quantity: 'quantity',
  price: 'price',
  revenue: 'revenue',
  barcode: 'barcode',
  code: 'code',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StocksScalarFieldEnum = (typeof StocksScalarFieldEnum)[keyof typeof StocksScalarFieldEnum]


export const AssetsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  quantity: 'quantity',
  price: 'price',
  barcode: 'barcode',
  code: 'code',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AssetsScalarFieldEnum = (typeof AssetsScalarFieldEnum)[keyof typeof AssetsScalarFieldEnum]


export const DepartmentsScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type DepartmentsScalarFieldEnum = (typeof DepartmentsScalarFieldEnum)[keyof typeof DepartmentsScalarFieldEnum]


export const EmployeesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  role: 'role',
  code: 'code',
  active: 'active',
  designation: 'designation',
  email: 'email',
  phone: 'phone',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  departmentId: 'departmentId'
} as const

export type EmployeesScalarFieldEnum = (typeof EmployeesScalarFieldEnum)[keyof typeof EmployeesScalarFieldEnum]


export const SuppliersScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SuppliersScalarFieldEnum = (typeof SuppliersScalarFieldEnum)[keyof typeof SuppliersScalarFieldEnum]


export const NotificationsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationsScalarFieldEnum = (typeof NotificationsScalarFieldEnum)[keyof typeof NotificationsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  users?: Prisma.UsersOmit
  tokens?: Prisma.TokensOmit
  companies?: Prisma.CompaniesOmit
  invoices?: Prisma.InvoicesOmit
  invoiceViewers?: Prisma.InvoiceViewersOmit
  invoiceEditors?: Prisma.InvoiceEditorsOmit
  transactionCategories?: Prisma.TransactionCategoriesOmit
  transactions?: Prisma.TransactionsOmit
  records?: Prisma.RecordsOmit
  stocks?: Prisma.StocksOmit
  assets?: Prisma.AssetsOmit
  departments?: Prisma.DepartmentsOmit
  employees?: Prisma.EmployeesOmit
  suppliers?: Prisma.SuppliersOmit
  notifications?: Prisma.NotificationsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

